/**
 * Design tokens: the single source of truth for every value in ui-tokens.md.
 * The values come from the Claude Design prototype (design/Marshal.dc.html).
 * `pnpm gen` turns this file into CSS variables and the Tailwind theme.
 * Never edit the files in dist/ by hand.
 */

export type ThemeName = "light" | "dark";

/** Color, chart, and elevation tokens that change with the theme. */
export interface ThemeTokens {
  colors: Record<string, string>;
  charts: Record<string, string>;
  elevations: Record<string, string>;
}

export const themes: Record<ThemeName, ThemeTokens> = {
  light: {
    colors: {
      "color-canvas": "#F5F6F7",
      "color-surface": "#FFFFFF",
      "color-surface-sunken": "#EEF0F2",
      "color-surface-raised": "#FFFFFF",
      "color-surface-hover": "#F0F2F4",
      "color-surface-selected": "#E7EAED",
      "color-border": "#E1E4E8",
      "color-border-strong": "#C9CED4",
      "color-text-primary": "#16191D",
      "color-text-secondary": "#4C535C",
      "color-text-muted": "#6A727B",
      "color-text-inverse": "#F5F6F7",
      "color-ink": "#16191D",
      "color-ink-hover": "#2A2F35",
      "color-on-ink": "#FFFFFF",
      "color-status-planning-solid": "#8A929B",
      "color-status-planning-text": "#4C535C",
      "color-status-planning-subtle": "#F1F3F5",
      "color-status-working-solid": "#1E9E5A",
      "color-status-working-text": "#146C3E",
      "color-status-working-subtle": "#E7F5EC",
      "color-status-needs-you-solid": "#BF8700",
      "color-status-needs-you-text": "#7F5A00",
      "color-status-needs-you-subtle": "#FCF4DC",
      "color-status-review-solid": "#2E6BD9",
      "color-status-review-text": "#1F4FA8",
      "color-status-review-subtle": "#E8EFFC",
      "color-status-ready-solid": "#0F97A0",
      "color-status-ready-text": "#0A6A71",
      "color-status-ready-subtle": "#E3F4F5",
      "color-status-done-solid": "#16191D",
      "color-status-done-text": "#4C535C",
      "color-status-done-subtle": "#F1F3F5",
      "color-status-danger-solid": "#D53B3B",
      "color-status-danger-text": "#A32323",
      "color-status-danger-subtle": "#FBEAEA",
      "color-bypass-bg": "#B42323",
      "color-bypass-stripe": "#9C1C1C",
      "color-bypass-text": "#FFFFFF",
      "color-diff-added-bg": "#E7F5EC",
      "color-diff-added-line": "#CDEBD8",
      "color-diff-added-text": "#146C3E",
      "color-diff-removed-bg": "#FBEAEA",
      "color-diff-removed-line": "#F4D2D2",
      "color-diff-removed-text": "#A32323",
    },
    charts: {
      "chart-1": "#16191D",
      "chart-2": "#6A727B",
      "chart-3": "#A7AEB6",
      "chart-4": "#C9CED4",
      "chart-grid": "#E1E4E8",
      "chart-axis": "#6A727B",
      "chart-limit": "#D53B3B",
    },
    elevations: {
      "elevation-1": "0 6px 16px -4px rgb(22 25 29 / 0.16)",
      "elevation-2": "0 16px 40px -8px rgb(22 25 29 / 0.24)",
      "elevation-drag": "0 10px 24px -6px rgb(22 25 29 / 0.22)",
    },
  },
  dark: {
    colors: {
      "color-canvas": "#15181C",
      "color-surface": "#1B1F24",
      "color-surface-sunken": "#111417",
      "color-surface-raised": "#22272D",
      "color-surface-hover": "#242A31",
      "color-surface-selected": "#2A3139",
      "color-border": "#2B3138",
      "color-border-strong": "#3A424B",
      "color-text-primary": "#E8EBEE",
      "color-text-secondary": "#A8B0B9",
      "color-text-muted": "#858D96",
      "color-text-inverse": "#15181C",
      "color-ink": "#E8EBEE",
      "color-ink-hover": "#FFFFFF",
      "color-on-ink": "#15181C",
      "color-status-planning-solid": "#6B737D",
      "color-status-planning-text": "#A8B0B9",
      "color-status-planning-subtle": "#20252B",
      "color-status-working-solid": "#3DBE7A",
      "color-status-working-text": "#6FD69E",
      "color-status-working-subtle": "#15291F",
      "color-status-needs-you-solid": "#F2B81F",
      "color-status-needs-you-text": "#F5CC5C",
      "color-status-needs-you-subtle": "#2E2610",
      "color-status-review-solid": "#5B8DEF",
      "color-status-review-text": "#8DB0F5",
      "color-status-review-subtle": "#182338",
      "color-status-ready-solid": "#2BB6BF",
      "color-status-ready-text": "#6BD0D6",
      "color-status-ready-subtle": "#11292C",
      "color-status-done-solid": "#E8EBEE",
      "color-status-done-text": "#A8B0B9",
      "color-status-done-subtle": "#20252B",
      "color-status-danger-solid": "#EF5A5A",
      "color-status-danger-text": "#F58A8A",
      "color-status-danger-subtle": "#331A1B",
      "color-bypass-bg": "#C83A3A",
      "color-bypass-stripe": "#A92E2E",
      "color-bypass-text": "#FFFFFF",
      "color-diff-added-bg": "#15291F",
      "color-diff-added-line": "#1D3A2B",
      "color-diff-added-text": "#6FD69E",
      "color-diff-removed-bg": "#331A1B",
      "color-diff-removed-line": "#4A2224",
      "color-diff-removed-text": "#F58A8A",
    },
    charts: {
      "chart-1": "#E8EBEE",
      "chart-2": "#A8B0B9",
      "chart-3": "#6B737D",
      "chart-4": "#3A424B",
      "chart-grid": "#2B3138",
      "chart-axis": "#858D96",
      "chart-limit": "#EF5A5A",
    },
    elevations: {
      "elevation-1": "0 6px 16px -4px rgb(0 0 0 / 0.5)",
      "elevation-2": "0 16px 40px -8px rgb(0 0 0 / 0.6)",
      "elevation-drag": "0 10px 24px -6px rgb(0 0 0 / 0.55)",
    },
  },
};
