/**
 * Builds the text of src/index.ts from the package's source files. Shared by
 * gen-index.mjs, which writes the file, and src/index.test.ts, which checks it
 * is up to date. The output already matches Biome's format and export order.
 *
 * Only named declarations are exported: `export function`, `export const`,
 * `export interface`, and `export type`. Test files, index.ts, test-setup.ts,
 * and files whose name starts with `_` are private.
 */

const LINE_WIDTH = 100;
const VALUE_EXPORT =
  /^export\s+(?:async\s+)?(?:function\*?|const|let|class|enum)\s+([A-Za-z_$][\w$]*)/gm;
const TYPE_EXPORT = /^export\s+(?:interface|type)\s+([A-Za-z_$][\w$]*)/gm;
const HEADER = "// Generated by scripts/gen-index.mjs from src/. Do not edit. Run `pnpm gen`.\n";

/** Path is relative to src/, with forward slashes, for example `base/Button.tsx`. */
export function isPublicModule(path) {
  const name = path.split("/").pop() ?? "";
  if (!/\.tsx?$/.test(name) || /\.test\.tsx?$/.test(name)) return false;
  return !name.startsWith("_") && path !== "index.ts" && name !== "test-setup.ts";
}

/**
 * Biome's order: letters compare without case, and at the first place two
 * names differ only in case, the upper case letter comes first.
 */
function biomeOrder(a, b) {
  const length = Math.min(a.length, b.length);
  for (let i = 0; i < length; i++) {
    if (a[i] === b[i]) continue;
    const x = a[i].toLowerCase();
    const y = b[i].toLowerCase();
    if (x !== y) return x < y ? -1 : 1;
    return a[i] === a[i].toUpperCase() ? -1 : 1;
  }
  return a.length - b.length;
}

function namesIn(code, pattern) {
  return [...code.matchAll(pattern)].map((match) => match[1]);
}

function exportLine(specifier, values, types) {
  const typeOnly = values.length === 0;
  const names = [...values, ...types].sort(biomeOrder).map((name) => {
    return typeOnly || values.includes(name) ? name : `type ${name}`;
  });
  const keyword = typeOnly ? "export type" : "export";
  const oneLine = `${keyword} { ${names.join(", ")} } from "${specifier}";`;
  if (oneLine.length <= LINE_WIDTH) return oneLine;
  return `${keyword} {\n${names.map((n) => `  ${n},`).join("\n")}\n} from "${specifier}";`;
}

/** @param {{ path: string, code: string }[]} modules */
export function buildIndex(modules) {
  const lines = modules
    .filter((m) => isPublicModule(m.path))
    .map((m) => ({
      specifier: `./${m.path.replace(/\.tsx?$/, "")}`,
      values: namesIn(m.code, VALUE_EXPORT),
      types: namesIn(m.code, TYPE_EXPORT),
    }))
    .filter((m) => m.values.length + m.types.length > 0)
    .sort((a, b) => biomeOrder(a.specifier, b.specifier))
    .map((m) => exportLine(m.specifier, m.values, m.types));
  return `${HEADER}${lines.join("\n")}\n`;
}
