/**
 * Generates dist/tokens.css and dist/tailwind-theme.css from src/*.ts.
 * Run with `pnpm gen`. Never edit the generated files by hand.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { themes } from "../src/themes.ts";
import {
  breakpoints,
  durations,
  easings,
  fonts,
  keyframes,
  layers,
  radii,
  sizes,
  spacingStep,
  staticColors,
  textSizes,
} from "../src/tokens.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
const banner = "/* Generated by packages/tokens/scripts/build-css.ts. Do not edit. */\n";

const lines = (entries: [string, string | number][], indent = "  ") =>
  entries.map(([name, value]) => `${indent}--${name}: ${value};`).join("\n");

/** Text color aliases so `text-primary` and `text-secondary` read naturally. */
const textAliases: [string, string][] = [
  ["color-primary", "var(--color-text-primary)"],
  ["color-secondary", "var(--color-text-secondary)"],
  ["color-muted", "var(--color-text-muted)"],
  ["color-inverse", "var(--color-text-inverse)"],
];

function themeBlock(selector: string, theme: keyof typeof themes): string {
  const t = themes[theme];
  const entries: [string, string][] = [
    ...Object.entries(t.colors),
    ...Object.entries(t.charts),
    ...Object.entries(t.elevations),
  ];
  return `${selector} {\n${lines(entries)}\n  color-scheme: ${theme};\n}\n`;
}

/** Runtime variables. Light values live in the Tailwind theme, so only dark overrides go here. */
function tokensCss(): string {
  return [banner, themeBlock('[data-theme="dark"]', "dark")].join("\n");
}

function colorTheme(): string {
  const light = themes.light;
  const colors = Object.entries(light.colors).map(([n, v]): [string, string] => [n, v]);
  const charts = Object.entries(light.charts);
  const elevations = Object.entries(light.elevations);
  const fixed = Object.entries(staticColors).map(([n, v]): [string, string] => [`color-${n}`, v]);
  const chartColors = charts.map(([n]): [string, string] => [`color-${n}`, `var(--${n})`]);
  return [
    "  --color-*: initial;",
    lines(colors),
    lines(textAliases),
    lines(fixed),
    lines(chartColors),
    lines(charts),
    lines(elevations),
  ].join("\n");
}

function scaleTheme(): string {
  const text = Object.entries(textSizes).map(([n, px]): [string, string] => [`text-${n}`, `${px}px`]);
  const radius = Object.entries(radii).map(([n, px]): [string, string] => [`radius-${n}`, `${px}px`]);
  const container = Object.entries(sizes).map(([n, px]): [string, string] => [`container-${n}`, `${px}px`]);
  const bps = Object.entries(breakpoints).map(([n, px]): [string, string] => [`breakpoint-${n}`, `${px}px`]);
  const ease = Object.entries(easings).map(([n, v]): [string, string] => [`ease-${n}`, v]);
  return [
    "  --text-*: initial;",
    lines(text),
    "  --radius-*: initial;",
    lines(radius),
    "  --container-*: initial;",
    lines(container),
    "  --breakpoint-*: initial;",
    lines(bps),
    "  --ease-*: initial;",
    lines(ease),
    `  --spacing: ${spacingStep}px;`,
    `  --font-*: initial;`,
    `  --font-sans: ${fonts.sans};`,
    `  --font-mono: ${fonts.mono};`,
    "  --shadow-*: initial;",
    "  --shadow-e1: var(--elevation-1);",
    "  --shadow-e2: var(--elevation-2);",
    "  --shadow-drag: var(--elevation-drag);",
    "  --animate-*: initial;",
    `  --animate-pulse-working: m-pulse 1600ms ease-in-out infinite;`,
    `  --animate-spin-fast: m-spin 800ms linear infinite;`,
  ].join("\n");
}

function utilities(): string {
  const z = Object.entries(layers).map(([n, v]) => `@utility z-${n} {\n  z-index: ${v};\n}`);
  const d = Object.entries(durations).map(
    ([n, v]) => `@utility duration-${n} {\n  transition-duration: ${v}ms;\n}`,
  );
  const kf = Object.entries(keyframes).map(([n, body]) => `@keyframes ${n} {\n  ${body}\n}`);
  return [...z, ...d, ...kf].join("\n\n");
}

function tailwindCss(): string {
  return `${banner}@theme static {\n${colorTheme()}\n${scaleTheme()}\n}\n\n${utilities()}\n`;
}

mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, "tokens.css"), tokensCss());
writeFileSync(join(dist, "tailwind-theme.css"), tailwindCss());
console.log("tokens: wrote dist/tokens.css and dist/tailwind-theme.css");
