// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (id, user_id, name, kind, token_hash, paired_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDeviceParams struct {
	ID        string
	UserID    string
	Name      string
	Kind      string
	TokenHash string
	PairedAt  int64
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.TokenHash,
		arg.PairedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, avatar_path, time_zone, tailnet_identity, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, email, avatar_path, time_zone, tailnet_identity, created_at, updated_at
`

type CreateUserParams struct {
	ID              string
	Name            string
	Email           string
	AvatarPath      string
	TimeZone        string
	TailnetIdentity string
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarPath,
		arg.TimeZone,
		arg.TailnetIdentity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarPath,
		&i.TimeZone,
		&i.TailnetIdentity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveDeviceByTokenHash = `-- name: GetActiveDeviceByTokenHash :one
SELECT id, user_id, name, kind, token_hash, paired_at, last_seen_at, revoked_at FROM devices WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetActiveDeviceByTokenHash(ctx context.Context, tokenHash string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getActiveDeviceByTokenHash, tokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.TokenHash,
		&i.PairedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOwner = `-- name: GetOwner :one
SELECT id, name, email, avatar_path, time_zone, tailnet_identity, created_at, updated_at FROM users ORDER BY created_at, id LIMIT 1
`

func (q *Queries) GetOwner(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getOwner)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarPath,
		&i.TimeZone,
		&i.TailnetIdentity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, user_id, name, kind, paired_at, last_seen_at, revoked_at
FROM devices
WHERE user_id = ?
ORDER BY paired_at, id
`

type ListDevicesRow struct {
	ID         string
	UserID     string
	Name       string
	Kind       string
	PairedAt   int64
	LastSeenAt *int64
	RevokedAt  *int64
}

func (q *Queries) ListDevices(ctx context.Context, userID string) ([]ListDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesRow{}
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.PairedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :execrows
UPDATE devices SET revoked_at = CAST(?1 AS INTEGER)
WHERE id = ?2 AND revoked_at IS NULL
`

type RevokeDeviceParams struct {
	RevokedAt int64
	ID        string
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeDevice, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen_at = CAST(?1 AS INTEGER)
WHERE id = ?2 AND revoked_at IS NULL
`

type TouchDeviceParams struct {
	LastSeenAt int64
	ID         string
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.ExecContext(ctx, touchDevice, arg.LastSeenAt, arg.ID)
	return err
}
