// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"
)

const deleteActivityForProject = `-- name: DeleteActivityForProject :exec
DELETE FROM activity WHERE project_id = ?
`

// Drops a project's rows when the project is removed from Marshal. The table has no foreign key on
// project_id (an empty string means "no project"), so the module that owns the stream removes them
// itself when project.removed arrives.
func (q *Queries) DeleteActivityForProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteActivityForProject, projectID)
	return err
}

const insertActivity = `-- name: InsertActivity :exec

INSERT INTO activity (id, seq, project_id, kind, subject_kind, subject_id, subject_key, summary, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertActivityParams struct {
	ID          string
	Seq         int64
	ProjectID   string
	Kind        string
	SubjectKind string
	SubjectID   string
	SubjectKey  string
	Summary     string
	CreatedAt   int64
}

// The Home activity stream (migration 0008, docs/backend-checklist.md B2.3, inventory N17). The
// dashboard module's subscriber appends rows as the daemon's events arrive and trims them after
// ninety days; the view-all route reads them newest first, one page at a time, filtered by kind
// and by project. A page is read by cursor (`seq`), never by offset, so a row appended while a
// client pages does not shift what it has already seen.
// Appends one row of the stream. Run it in the same transaction as NextActivitySeq and the
// daily_stats update that goes with it, so the stream's order and the numbers stay together.
func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.ID,
		arg.Seq,
		arg.ProjectID,
		arg.Kind,
		arg.SubjectKind,
		arg.SubjectID,
		arg.SubjectKey,
		arg.Summary,
		arg.CreatedAt,
	)
	return err
}

const listActivity = `-- name: ListActivity :many

SELECT id, seq, project_id, kind, subject_kind, subject_id, subject_key, summary, created_at FROM activity
WHERE seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListActivityParams struct {
	Seq   int64
	Limit int64
}

// Every read below selects the whole table, so sqlc gives them all the table's own row type
// (`db.Activity`) and one Go mapper serves them. `seq < ?` is the cursor: pass a number larger than
// any seq for the newest page, and the seq the previous page ended on for the page after it. A
// filter that is not wanted is left out of the WHERE clause rather than passed as a wildcard, so
// each kind of page uses its own index.
func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivity, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ProjectID,
			&i.Kind,
			&i.SubjectKind,
			&i.SubjectID,
			&i.SubjectKey,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityByKind = `-- name: ListActivityByKind :many
SELECT id, seq, project_id, kind, subject_kind, subject_id, subject_key, summary, created_at FROM activity
WHERE kind = ? AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListActivityByKindParams struct {
	Kind  string
	Seq   int64
	Limit int64
}

func (q *Queries) ListActivityByKind(ctx context.Context, arg ListActivityByKindParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivityByKind, arg.Kind, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ProjectID,
			&i.Kind,
			&i.SubjectKind,
			&i.SubjectID,
			&i.SubjectKey,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityByKindAndProject = `-- name: ListActivityByKindAndProject :many
SELECT id, seq, project_id, kind, subject_kind, subject_id, subject_key, summary, created_at FROM activity
WHERE kind = ? AND project_id = ? AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListActivityByKindAndProjectParams struct {
	Kind      string
	ProjectID string
	Seq       int64
	Limit     int64
}

func (q *Queries) ListActivityByKindAndProject(ctx context.Context, arg ListActivityByKindAndProjectParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivityByKindAndProject,
		arg.Kind,
		arg.ProjectID,
		arg.Seq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ProjectID,
			&i.Kind,
			&i.SubjectKind,
			&i.SubjectID,
			&i.SubjectKey,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityByProject = `-- name: ListActivityByProject :many
SELECT id, seq, project_id, kind, subject_kind, subject_id, subject_key, summary, created_at FROM activity
WHERE project_id = ? AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListActivityByProjectParams struct {
	ProjectID string
	Seq       int64
	Limit     int64
}

func (q *Queries) ListActivityByProject(ctx context.Context, arg ListActivityByProjectParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivityByProject, arg.ProjectID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ProjectID,
			&i.Kind,
			&i.SubjectKind,
			&i.SubjectID,
			&i.SubjectKey,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextActivitySeq = `-- name: NextActivitySeq :one
SELECT CAST(COALESCE(MAX(seq), 0) + 1 AS INTEGER) AS seq FROM activity
`

// The seq the next row of the stream takes. One stream covers every project, so this is the
// newest seq in the table and not a per-project number. Run it in the same transaction as the
// insert, so two rows cannot take one number.
func (q *Queries) NextActivitySeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextActivitySeq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const trimActivity = `-- name: TrimActivity :exec
DELETE FROM activity WHERE created_at < ?
`

// Drops the rows older than the moment given, which is what "trimmed after ninety days" is. It is
// one range delete on activity_created_at, and it is what keeps the stream bounded.
func (q *Queries) TrimActivity(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, trimActivity, createdAt)
	return err
}
