// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package db

import (
	"context"
)

const createApproval = `-- name: CreateApproval :exec
INSERT INTO approvals (id, session_id, request_json) VALUES (?, ?, ?)
`

type CreateApprovalParams struct {
	ID          string
	SessionID   string
	RequestJSON string
}

// The insert the session pump makes the moment an agent asks for permission, before the request is
// announced. decision and decided_by keep their defaults (empty, meaning nobody has answered yet).
func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) error {
	_, err := q.db.ExecContext(ctx, createApproval, arg.ID, arg.SessionID, arg.RequestJSON)
	return err
}

const decideApproval = `-- name: DecideApproval :execrows
UPDATE approvals SET decision = ?1, decided_by = ?2
WHERE id = ?3 AND decision = ''
`

type DecideApprovalParams struct {
	Decision  string
	DecidedBy string
	ID        string
}

// The one write that answers a request. The `decision = ”` guard makes it the only answer: a second
// call for a request that is already decided changes nothing and reports zero rows, which the caller
// treats as "already answered" rather than overwriting the first decision.
func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideApproval, arg.Decision, arg.DecidedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getApproval = `-- name: GetApproval :one
SELECT id, session_id, request_json, decision, decided_by FROM approvals WHERE id = ?
`

func (q *Queries) GetApproval(ctx context.Context, id string) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestJSON,
		&i.Decision,
		&i.DecidedBy,
	)
	return i, err
}
