// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const exportAuditLog = `-- name: ExportAuditLog :many
SELECT id, session_id, actor, "action", target, detail_json, created_at FROM audit_log ORDER BY created_at DESC, id DESC LIMIT ?1
`

// Every row, newest first, for an export: no paging, so the file holds the whole answer. The limit
// is a ceiling on how much one export may carry, not a page size.
func (q *Queries) ExportAuditLog(ctx context.Context, exportLimit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, exportAuditLog, exportLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.DetailJSON,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, session_id, actor, action, target, detail_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	ID         string
	SessionID  string
	Actor      string
	Action     string
	Target     string
	DetailJSON string
	CreatedAt  int64
}

// One row per action worth accounting for (docs/architecture.md section 10). Append only: the API
// never edits or deletes one. The id is an opaque id made by the caller, so it sorts by time like
// every other id.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.ID,
		arg.SessionID,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.DetailJSON,
		arg.CreatedAt,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, session_id, actor, "action", target, detail_json, created_at FROM audit_log ORDER BY rowid DESC LIMIT ?
`

// The newest rows first. The order is the rowid's, which is the order the rows were written in: two
// rows written in the same millisecond share a time, and their ids share everything but random bits,
// so neither orders them. A test reads this to prove a row was written.
func (q *Queries) ListAuditLog(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.DetailJSON,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogPage = `-- name: ListAuditLogPage :many
SELECT id, session_id, actor, "action", target, detail_json, created_at FROM audit_log
WHERE created_at < ?1
   OR (created_at = ?1 AND id < ?2)
ORDER BY created_at DESC, id DESC
LIMIT ?3
`

type ListAuditLogPageParams struct {
	BeforeTime int64
	BeforeID   string
	PageLimit  int64
}

// One page of the audit log, newest first, paged by (created_at, id) - the pair the table already
// indexes - rather than by rowid, which a query may order by but not compare (SQLite's rowid is not
// a declared column, so sqlc refuses it in a WHERE). The pair is unique because the id is, so the
// order is total and stable. The newest page asks for rows before the end of time with an empty id,
// which is every row.
func (q *Queries) ListAuditLogPage(ctx context.Context, arg ListAuditLogPageParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogPage, arg.BeforeTime, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.DetailJSON,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuditLogExport = `-- name: SearchAuditLogExport :many
SELECT id, session_id, actor, "action", target, detail_json, created_at FROM audit_log
WHERE actor LIKE ?1 OR action LIKE ?1
   OR target LIKE ?1 OR detail_json LIKE ?1
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type SearchAuditLogExportParams struct {
	Pattern     string
	ExportLimit int64
}

// Every row a search matched, newest first, for an export: the same search as SearchAuditLogPage,
// with no paging.
func (q *Queries) SearchAuditLogExport(ctx context.Context, arg SearchAuditLogExportParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, searchAuditLogExport, arg.Pattern, arg.ExportLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.DetailJSON,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuditLogPage = `-- name: SearchAuditLogPage :many
SELECT id, session_id, actor, "action", target, detail_json, created_at FROM audit_log
WHERE (created_at < ?1
       OR (created_at = ?1 AND id < ?2))
  AND (actor LIKE ?3 OR action LIKE ?3
       OR target LIKE ?3 OR detail_json LIKE ?3)
ORDER BY created_at DESC, id DESC
LIMIT ?4
`

type SearchAuditLogPageParams struct {
	BeforeTime int64
	BeforeID   string
	Pattern    string
	PageLimit  int64
}

// The rows a search matched, newest first, paged the same way as ListAuditLogPage. The search reads
// the four columns a person can search by - actor, action, target, and the recorded detail - and is
// told the pattern to use ('%word%'). A `%` or `_` in a person's words acts as the SQL wildcard it
// looks like, which widens a search rather than failing it.
func (q *Queries) SearchAuditLogPage(ctx context.Context, arg SearchAuditLogPageParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, searchAuditLogPage,
		arg.BeforeTime,
		arg.BeforeID,
		arg.Pattern,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.DetailJSON,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
