// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card_links.sql

package db

import (
	"context"
)

const insertCardLink = `-- name: InsertCardLink :exec

INSERT INTO card_links (card_id, depends_on_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type InsertCardLinkParams struct {
	CardID      string
	DependsOnID string
}

// Card dependencies: the edges of a plan (docs/architecture.md section 10, migration 0020,
// build-plan task 7.4). The Orchestrator makes them as it creates cards from a goal; the board and
// a card's own panel read them back.
// Writing the same edge twice is not an error: a card's dependencies are set, not appended, and a
// caller that repeats one is saying the same thing.
func (q *Queries) InsertCardLink(ctx context.Context, arg InsertCardLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertCardLink, arg.CardID, arg.DependsOnID)
	return err
}

const listCardDependencyNumbers = `-- name: ListCardDependencyNumbers :many
SELECT dep.number
FROM card_links AS link
JOIN cards AS dep ON dep.id = link.depends_on_id
WHERE link.card_id = ?
ORDER BY dep.number
`

// The numbers of the cards one card waits for, in number order. Keys are built from the project id
// and a number (protocol.CardKey), so the number is what the caller needs and the join is what
// gives it.
func (q *Queries) ListCardDependencyNumbers(ctx context.Context, cardID string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCardDependencyNumbers, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDependencies = `-- name: ListProjectDependencies :many
SELECT link.card_id AS card_id, dep.number AS depends_on_number
FROM card_links AS link
JOIN cards AS card ON card.id = link.card_id
JOIN cards AS dep ON dep.id = link.depends_on_id
WHERE card.project_id = ?
ORDER BY card.number, dep.number
`

type ListProjectDependenciesRow struct {
	CardID          string
	DependsOnNumber int64
}

// Every edge in one project, as the pair (the card, the number of the card it waits for). It is one
// query for the whole board rather than one per card, because the board summary and the awareness
// summary both read every card's dependencies at once.
func (q *Queries) ListProjectDependencies(ctx context.Context, projectID string) ([]ListProjectDependenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectDependencies, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectDependenciesRow{}
	for rows.Next() {
		var i ListProjectDependenciesRow
		if err := rows.Scan(&i.CardID, &i.DependsOnNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
