// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card_checks.sql

package db

import (
	"context"
)

const countCardChecks = `-- name: CountCardChecks :one
SELECT COUNT(*) FROM card_checks WHERE card_id = ?
`

// How many checks a card has, for a card that is about to be created from a template.
func (q *Queries) CountCardChecks(ctx context.Context, cardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardChecks, cardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnpassedChecks = `-- name: CountUnpassedChecks :one
SELECT COUNT(*) FROM card_checks WHERE card_id = ? AND status <> 'passed'
`

// How many of a card's checks have not passed. This is the whole of the gate: a card cannot finish
// until it is zero, and the number is what a screen shows when it says what is left.
func (q *Queries) CountUnpassedChecks(ctx context.Context, cardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnpassedChecks, cardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCardCheck = `-- name: CreateCardCheck :exec

INSERT INTO card_checks (id, card_id, kind, spec_json, status, run_ref, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCardCheckParams struct {
	ID        string
	CardID    string
	Kind      string
	SpecJSON  string
	Status    string
	RunRef    string
	CreatedAt int64
	UpdatedAt int64
}

// A card's acceptance checks (migration 0024, docs/architecture.md section 10's `card_checks` row
// and section 19; docs/backend-checklist.md B10.2, build-plan task 10.4, inventory N9).
//
// A check is one thing Marshal runs about a card - a test, a linter, a link - and the gate a card
// has to pass before it can finish. Its `status` is also the evidence a checklist item can be
// ticked with, which is why `run_ref` travels with it: a tick proven by run 118 must know it is
// still looking at run 118 and not at run 119.
func (q *Queries) CreateCardCheck(ctx context.Context, arg CreateCardCheckParams) error {
	_, err := q.db.ExecContext(ctx, createCardCheck,
		arg.ID,
		arg.CardID,
		arg.Kind,
		arg.SpecJSON,
		arg.Status,
		arg.RunRef,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCardCheck = `-- name: DeleteCardCheck :exec
DELETE FROM card_checks WHERE id = ?
`

func (q *Queries) DeleteCardCheck(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCardCheck, id)
	return err
}

const getCardCheck = `-- name: GetCardCheck :one
SELECT id, card_id, kind, spec_json, status, run_ref, created_at, updated_at FROM card_checks WHERE id = ?
`

func (q *Queries) GetCardCheck(ctx context.Context, id string) (CardCheck, error) {
	row := q.db.QueryRowContext(ctx, getCardCheck, id)
	var i CardCheck
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Kind,
		&i.SpecJSON,
		&i.Status,
		&i.RunRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardChecks = `-- name: ListCardChecks :many
SELECT id, card_id, kind, spec_json, status, run_ref, created_at, updated_at FROM card_checks WHERE card_id = ? ORDER BY created_at, id
`

// One card's checks, in the order they are drawn.
func (q *Queries) ListCardChecks(ctx context.Context, cardID string) ([]CardCheck, error) {
	rows, err := q.db.QueryContext(ctx, listCardChecks, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardCheck{}
	for rows.Next() {
		var i CardCheck
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Kind,
			&i.SpecJSON,
			&i.Status,
			&i.RunRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardCheckStatus = `-- name: UpdateCardCheckStatus :exec
UPDATE card_checks
SET status = ?, run_ref = ?, updated_at = ?
WHERE id = ?
`

type UpdateCardCheckStatusParams struct {
	Status    string
	RunRef    string
	UpdatedAt int64
	ID        string
}

// Records what a run found, and which run it was. `run_ref` moves with the status in the same
// statement, so a status can never be left describing an older answer than the reference beside it.
func (q *Queries) UpdateCardCheckStatus(ctx context.Context, arg UpdateCardCheckStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCardCheckStatus,
		arg.Status,
		arg.RunRef,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
