// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"
)

const listMergeBranches = `-- name: ListMergeBranches :many
SELECT id, state, branch, merge_phase
FROM cards
WHERE project_id = ? AND branch <> '' AND state <> 'done'
ORDER BY number
`

type ListMergeBranchesRow struct {
	ID         string
	State      string
	Branch     string
	MergePhase string
}

// The cards of a project that have a branch and are not done, with their state. It is how the
// Integrator finds which cards the work waiting on its branch belongs to, and which of them have
// been pulled back since.
func (q *Queries) ListMergeBranches(ctx context.Context, projectID string) ([]ListMergeBranchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMergeBranches, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergeBranchesRow{}
	for rows.Next() {
		var i ListMergeBranchesRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Branch,
			&i.MergePhase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMergeQueue = `-- name: ListMergeQueue :many
SELECT id, project_id, number, title, state, branch, merge_phase, merge_note, updated_at
FROM cards
WHERE project_id = ? AND state IN ('ready', 'merging')
ORDER BY CASE state WHEN 'merging' THEN 0 ELSE 1 END, updated_at, number
`

type ListMergeQueueRow struct {
	ID         string
	ProjectID  string
	Number     int64
	Title      string
	State      string
	Branch     string
	MergePhase string
	MergeNote  string
	UpdatedAt  int64
}

// The cards of a project that wait for a merge or are being merged: the one being merged first, the
// rest in the order they became ready.
func (q *Queries) ListMergeQueue(ctx context.Context, projectID string) ([]ListMergeQueueRow, error) {
	rows, err := q.db.QueryContext(ctx, listMergeQueue, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergeQueueRow{}
	for rows.Next() {
		var i ListMergeQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.State,
			&i.Branch,
			&i.MergePhase,
			&i.MergeNote,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMergeStalled = `-- name: ListMergeStalled :many
SELECT id, project_id, number, title, state, branch, merge_phase, merge_note, updated_at,
       needs_reason_kind, needs_reason_text
FROM cards
WHERE project_id = ? AND state = 'needs' AND merge_phase = 'stopped'
  AND needs_reason_kind IN ('conflict', 'ci-failed')
ORDER BY updated_at DESC, number DESC
`

type ListMergeStalledRow struct {
	ID              string
	ProjectID       string
	Number          int64
	Title           string
	State           string
	Branch          string
	MergePhase      string
	MergeNote       string
	UpdatedAt       int64
	NeedsReasonKind string
	NeedsReasonText string
}

// The cards of a project that a merge stopped and a person has to look at, newest stop first. A
// stopped merge leaves the phase "stopped" and one of its two reasons on the card, so a card that
// was stopped once and now waits for another reason is not listed.
func (q *Queries) ListMergeStalled(ctx context.Context, projectID string) ([]ListMergeStalledRow, error) {
	rows, err := q.db.QueryContext(ctx, listMergeStalled, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergeStalledRow{}
	for rows.Next() {
		var i ListMergeStalledRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.State,
			&i.Branch,
			&i.MergePhase,
			&i.MergeNote,
			&i.UpdatedAt,
			&i.NeedsReasonKind,
			&i.NeedsReasonText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMergingCards = `-- name: ListMergingCards :many
SELECT id, project_id FROM cards WHERE state = 'merging' ORDER BY project_id, number
`

type ListMergingCardsRow struct {
	ID        string
	ProjectID string
}

// Every card, in any project, that is marked as being merged. After a restart none is, so these are
// the cards a crash left behind.
func (q *Queries) ListMergingCards(ctx context.Context) ([]ListMergingCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMergingCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergingCardsRow{}
	for rows.Next() {
		var i ListMergingCardsRow
		if err := rows.Scan(&i.ID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCardMergeProgress = `-- name: SetCardMergeProgress :execrows

UPDATE cards SET merge_phase = ?, merge_note = ?, doing_now = ? WHERE id = ?
`

type SetCardMergeProgressParams struct {
	MergePhase string
	MergeNote  string
	DoingNow   string
	ID         string
}

// The merge queue's reads and writes of the cards table (Integrator flow). The projects module owns
// a card's state and fields; the Integrator writes only the three columns that show a merge in
// progress, and reads the cards that are waiting for, in, or stopped by a merge.
// Sets where a card's merge is: the phase, the one sentence about it, and the card's "doing now"
// line. An empty phase means no merge is in progress. Every exit of a merge calls it, so a phase
// never outlives the merge. It leaves updated_at alone: the queue is ordered by when a card became
// ready, and the merge.progress event, not a new timestamp, tells clients the phase moved.
func (q *Queries) SetCardMergeProgress(ctx context.Context, arg SetCardMergeProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCardMergeProgress,
		arg.MergePhase,
		arg.MergeNote,
		arg.DoingNow,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
