// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package db

import (
	"context"
)

const archiveChat = `-- name: ArchiveChat :execrows
UPDATE chats SET archived_at = ?, updated_at = ? WHERE id = ?
`

type ArchiveChatParams struct {
	ArchivedAt *int64
	UpdatedAt  int64
	ID         string
}

func (q *Queries) ArchiveChat(ctx context.Context, arg ArchiveChatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveChat, arg.ArchivedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createChat = `-- name: CreateChat :exec
INSERT INTO chats (
    id, project_id, title, target_kind, target_id, agent_kind, model, thinking,
    permission_mode, archived_at, last_active_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateChatParams struct {
	ID             string
	ProjectID      string
	Title          string
	TargetKind     string
	TargetID       string
	AgentKind      string
	Model          string
	Thinking       string
	PermissionMode string
	ArchivedAt     *int64
	LastActiveAt   int64
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.ExecContext(ctx, createChat,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.TargetKind,
		arg.TargetID,
		arg.AgentKind,
		arg.Model,
		arg.Thinking,
		arg.PermissionMode,
		arg.ArchivedAt,
		arg.LastActiveAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteChat = `-- name: DeleteChat :execrows
DELETE FROM chats WHERE id = ?
`

func (q *Queries) DeleteChat(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChat, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChat = `-- name: GetChat :one
SELECT id, project_id, title, target_kind, target_id, agent_kind, model, thinking, permission_mode, archived_at, last_active_at, created_at, updated_at FROM chats WHERE id = ?
`

func (q *Queries) GetChat(ctx context.Context, id string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.TargetKind,
		&i.TargetID,
		&i.AgentKind,
		&i.Model,
		&i.Thinking,
		&i.PermissionMode,
		&i.ArchivedAt,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArchivedChatsByProject = `-- name: ListArchivedChatsByProject :many
SELECT id, project_id, title, target_kind, target_id, agent_kind, model, thinking, permission_mode, archived_at, last_active_at, created_at, updated_at FROM chats
WHERE project_id = ? AND archived_at IS NOT NULL
ORDER BY last_active_at DESC, id
`

// A project's archived chats, most recently active first. The live list and this one are two
// queries rather than one query with an optional archived_at, so neither has to cope with a NULL
// test whose answer is always the same.
func (q *Queries) ListArchivedChatsByProject(ctx context.Context, projectID string) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedChatsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chat{}
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.TargetKind,
			&i.TargetID,
			&i.AgentKind,
			&i.Model,
			&i.Thinking,
			&i.PermissionMode,
			&i.ArchivedAt,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatsByProject = `-- name: ListChatsByProject :many
SELECT id, project_id, title, target_kind, target_id, agent_kind, model, thinking, permission_mode, archived_at, last_active_at, created_at, updated_at FROM chats
WHERE project_id = ? AND archived_at IS NULL
ORDER BY last_active_at DESC, id
`

// A project's live chats: the ones in the main list, most recently active first.
func (q *Queries) ListChatsByProject(ctx context.Context, projectID string) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listChatsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chat{}
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.TargetKind,
			&i.TargetID,
			&i.AgentKind,
			&i.Model,
			&i.Thinking,
			&i.PermissionMode,
			&i.ArchivedAt,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameChat = `-- name: RenameChat :execrows
UPDATE chats SET title = ?, updated_at = ? WHERE id = ?
`

type RenameChatParams struct {
	Title     string
	UpdatedAt int64
	ID        string
}

func (q *Queries) RenameChat(ctx context.Context, arg RenameChatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameChat, arg.Title, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreChat = `-- name: RestoreChat :execrows
UPDATE chats SET archived_at = NULL, updated_at = ? WHERE id = ?
`

type RestoreChatParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) RestoreChat(ctx context.Context, arg RestoreChatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreChat, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchChat = `-- name: TouchChat :execrows
UPDATE chats SET last_active_at = ?, updated_at = ? WHERE id = ?
`

type TouchChatParams struct {
	LastActiveAt int64
	UpdatedAt    int64
	ID           string
}

// Moves a chat to the top of its project's list, once a message has been written to its session.
func (q *Queries) TouchChat(ctx context.Context, arg TouchChatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchChat, arg.LastActiveAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
