// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklists.sql

package db

import (
	"context"
)

const addCardMember = `-- name: AddCardMember :exec
INSERT INTO card_members (card_id, user_id, added_at) VALUES (?, ?, ?)
ON CONFLICT (card_id, user_id) DO NOTHING
`

type AddCardMemberParams struct {
	CardID  string
	UserID  string
	AddedAt int64
}

// Puts a person on a card. Adding one who is already on it is not an error: the card's membership is
// a set, not an append, and a second press from a second screen means the same thing.
func (q *Queries) AddCardMember(ctx context.Context, arg AddCardMemberParams) error {
	_, err := q.db.ExecContext(ctx, addCardMember, arg.CardID, arg.UserID, arg.AddedAt)
	return err
}

const countCardChecklists = `-- name: CountCardChecklists :one
SELECT COUNT(*) FROM checklists WHERE card_id = ?
`

// How many checklists a card has. A new one is put after them.
func (q *Queries) CountCardChecklists(ctx context.Context, cardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardChecklists, cardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenRequiredItems = `-- name: CountOpenRequiredItems :one
SELECT COUNT(*)
FROM checklist_items AS item
JOIN checklists AS checklist ON checklist.id = item.checklist_id
WHERE checklist.card_id = ? AND checklist.required = 1 AND item.done = 0
`

// How many open items sit on a card's required checklists. This is the number the merge queue is
// blocked by (docs/architecture.md section 19): a card cannot move to Ready to merge while it is
// more than zero, and when everything else is ready the card is sent to Needs you saying so.
func (q *Queries) CountOpenRequiredItems(ctx context.Context, cardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenRequiredItems, cardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChecklist = `-- name: CreateChecklist :exec

INSERT INTO checklists (id, card_id, name, position, required, people_only, hide_checked, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateChecklistParams struct {
	ID          string
	CardID      string
	Name        string
	Position    int64
	Required    int64
	PeopleOnly  int64
	HideChecked int64
	CreatedAt   int64
	UpdatedAt   int64
}

// Named checklists and their items, plus the people on a card (migration 0024,
// docs/architecture.md sections 10 and 19; docs/backend-checklist.md B10.5 and B10.6, build-plan
// tasks 10.10 to 10.13).
//
// The rules live in the service, not here: which checklists gate a merge, that a people-only one
// refuses an agent's tick, and that evidence is checked before a tick is saved. What the queries
// own is the order things are drawn in and the cascade that takes a card's checklists with it.
// Makes a checklist on a card. `position` is where it is drawn among the card's others; a new one
// goes last, which the service works out by counting what is already there.
func (q *Queries) CreateChecklist(ctx context.Context, arg CreateChecklistParams) error {
	_, err := q.db.ExecContext(ctx, createChecklist,
		arg.ID,
		arg.CardID,
		arg.Name,
		arg.Position,
		arg.Required,
		arg.PeopleOnly,
		arg.HideChecked,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createChecklistItem = `-- name: CreateChecklistItem :exec
INSERT INTO checklist_items (id, checklist_id, text, position, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateChecklistItemParams struct {
	ID          string
	ChecklistID string
	Text        string
	Position    int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) error {
	_, err := q.db.ExecContext(ctx, createChecklistItem,
		arg.ID,
		arg.ChecklistID,
		arg.Text,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteChecklist = `-- name: DeleteChecklist :exec
DELETE FROM checklists WHERE id = ?
`

// Removes a checklist and, by the cascade, its items. Deleting a checklist is not a step toward
// finishing a card; it is a person deciding the checks were wrong.
func (q *Queries) DeleteChecklist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChecklist, id)
	return err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :exec
DELETE FROM checklist_items WHERE id = ?
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChecklistItem, id)
	return err
}

const getChecklist = `-- name: GetChecklist :one
SELECT id, card_id, name, position, required, people_only, hide_checked, created_at, updated_at FROM checklists WHERE id = ?
`

func (q *Queries) GetChecklist(ctx context.Context, id string) (Checklist, error) {
	row := q.db.QueryRowContext(ctx, getChecklist, id)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Name,
		&i.Position,
		&i.Required,
		&i.PeopleOnly,
		&i.HideChecked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChecklistItem = `-- name: GetChecklistItem :one
SELECT id, checklist_id, text, position, done, done_by_kind, done_by_id, evidence_json, done_at, created_at, updated_at FROM checklist_items WHERE id = ?
`

func (q *Queries) GetChecklistItem(ctx context.Context, id string) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, getChecklistItem, id)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.Text,
		&i.Position,
		&i.Done,
		&i.DoneByKind,
		&i.DoneByID,
		&i.EvidenceJSON,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardChecklistItems = `-- name: ListCardChecklistItems :many
SELECT item.id, item.checklist_id, item.text, item.position, item.done, item.done_by_kind, item.done_by_id, item.evidence_json, item.done_at, item.created_at, item.updated_at, checklist.card_id AS card_id, checklist.required AS required,
       checklist.people_only AS people_only
FROM checklist_items AS item
JOIN checklists AS checklist ON checklist.id = item.checklist_id
WHERE checklist.card_id = ?
ORDER BY checklist.position, checklist.id, item.position, item.id
`

type ListCardChecklistItemsRow struct {
	ID           string
	ChecklistID  string
	Text         string
	Position     int64
	Done         int64
	DoneByKind   string
	DoneByID     string
	EvidenceJSON string
	DoneAt       *int64
	CreatedAt    int64
	UpdatedAt    int64
	CardID       string
	Required     int64
	PeopleOnly   int64
}

// Every item on a card, with its checklist's id and flags beside it. It is one read for the whole
// card rather than one per checklist, because a card's panel draws all of them at once and because
// the merge gate asks the same question over all of them.
func (q *Queries) ListCardChecklistItems(ctx context.Context, cardID string) ([]ListCardChecklistItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCardChecklistItems, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardChecklistItemsRow{}
	for rows.Next() {
		var i ListCardChecklistItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChecklistID,
			&i.Text,
			&i.Position,
			&i.Done,
			&i.DoneByKind,
			&i.DoneByID,
			&i.EvidenceJSON,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CardID,
			&i.Required,
			&i.PeopleOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardChecklists = `-- name: ListCardChecklists :many
SELECT id, card_id, name, position, required, people_only, hide_checked, created_at, updated_at FROM checklists WHERE card_id = ? ORDER BY position, id
`

// One card's checklists, in the order they are drawn.
func (q *Queries) ListCardChecklists(ctx context.Context, cardID string) ([]Checklist, error) {
	rows, err := q.db.QueryContext(ctx, listCardChecklists, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checklist{}
	for rows.Next() {
		var i Checklist
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Name,
			&i.Position,
			&i.Required,
			&i.PeopleOnly,
			&i.HideChecked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardMembers = `-- name: ListCardMembers :many
SELECT card_id, user_id, added_at FROM card_members WHERE card_id = ? ORDER BY added_at, user_id
`

// Who is on a card, oldest first, for the card's own row of people chips.
func (q *Queries) ListCardMembers(ctx context.Context, cardID string) ([]CardMember, error) {
	rows, err := q.db.QueryContext(ctx, listCardMembers, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardMember{}
	for rows.Next() {
		var i CardMember
		if err := rows.Scan(&i.CardID, &i.UserID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT id, checklist_id, text, position, done, done_by_kind, done_by_id, evidence_json, done_at, created_at, updated_at FROM checklist_items WHERE checklist_id = ? ORDER BY position, id
`

// One checklist's items, in the order they are drawn.
func (q *Queries) ListChecklistItems(ctx context.Context, checklistID string) ([]ChecklistItem, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistItems, checklistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistItem{}
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ChecklistID,
			&i.Text,
			&i.Position,
			&i.Done,
			&i.DoneByKind,
			&i.DoneByID,
			&i.EvidenceJSON,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCardMemberships = `-- name: ListUserCardMemberships :many
SELECT card_id, user_id, added_at FROM card_members WHERE user_id = ? ORDER BY added_at, card_id
`

// Which cards a person is on. It is what "my cards" reads, and what a member notice is sent to.
func (q *Queries) ListUserCardMemberships(ctx context.Context, userID string) ([]CardMember, error) {
	rows, err := q.db.QueryContext(ctx, listUserCardMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardMember{}
	for rows.Next() {
		var i CardMember
		if err := rows.Scan(&i.CardID, &i.UserID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCardMember = `-- name: RemoveCardMember :exec
DELETE FROM card_members WHERE card_id = ? AND user_id = ?
`

type RemoveCardMemberParams struct {
	CardID string
	UserID string
}

// Takes a person off a card. Removing one who is not on it is not an answer worth failing over.
func (q *Queries) RemoveCardMember(ctx context.Context, arg RemoveCardMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeCardMember, arg.CardID, arg.UserID)
	return err
}

const tickChecklistItem = `-- name: TickChecklistItem :exec
UPDATE checklist_items
SET done = ?, done_by_kind = ?, done_by_id = ?, evidence_json = ?, done_at = ?, updated_at = ?
WHERE id = ?
`

type TickChecklistItemParams struct {
	Done         int64
	DoneByKind   string
	DoneByID     string
	EvidenceJSON string
	DoneAt       *int64
	UpdatedAt    int64
	ID           string
}

// Ticks an item and records who ticked it and what proved it, or unticks it by passing a null
// `done_at` and an empty evidence. This is the one place a tick is written, so "who ticked this"
// and "with what evidence" can never disagree with `done`.
func (q *Queries) TickChecklistItem(ctx context.Context, arg TickChecklistItemParams) error {
	_, err := q.db.ExecContext(ctx, tickChecklistItem,
		arg.Done,
		arg.DoneByKind,
		arg.DoneByID,
		arg.EvidenceJSON,
		arg.DoneAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateChecklist = `-- name: UpdateChecklist :exec
UPDATE checklists
SET name = ?, required = ?, people_only = ?, hide_checked = ?, updated_at = ?
WHERE id = ?
`

type UpdateChecklistParams struct {
	Name        string
	Required    int64
	PeopleOnly  int64
	HideChecked int64
	UpdatedAt   int64
	ID          string
}

// Renames a checklist and sets its three flags. They are sent together because the screen edits
// them in one place, and because "required" and "people only" are the two that change what an agent
// is allowed to do - they belong in one place a person can read back.
func (q *Queries) UpdateChecklist(ctx context.Context, arg UpdateChecklistParams) error {
	_, err := q.db.ExecContext(ctx, updateChecklist,
		arg.Name,
		arg.Required,
		arg.PeopleOnly,
		arg.HideChecked,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateChecklistItemPosition = `-- name: UpdateChecklistItemPosition :exec
UPDATE checklist_items
SET position = ?, updated_at = ?
WHERE id = ?
`

type UpdateChecklistItemPositionParams struct {
	Position  int64
	UpdatedAt int64
	ID        string
}

// Moves one item. Reordering is its own call because dragging writes many positions and one item's
// text is nobody's business while that is happening.
func (q *Queries) UpdateChecklistItemPosition(ctx context.Context, arg UpdateChecklistItemPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateChecklistItemPosition, arg.Position, arg.UpdatedAt, arg.ID)
	return err
}

const updateChecklistItemText = `-- name: UpdateChecklistItemText :exec
UPDATE checklist_items
SET text = ?, updated_at = ?
WHERE id = ?
`

type UpdateChecklistItemTextParams struct {
	Text      string
	UpdatedAt int64
	ID        string
}

// Edits an item's words. The tick is untouched: rewording a check that has been ticked does not
// untick it, because what was proven has not changed.
func (q *Queries) UpdateChecklistItemText(ctx context.Context, arg UpdateChecklistItemTextParams) error {
	_, err := q.db.ExecContext(ctx, updateChecklistItemText, arg.Text, arg.UpdatedAt, arg.ID)
	return err
}
