// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package db

import (
	"context"
)

const countCheckpointsForCard = `-- name: CountCheckpointsForCard :one
SELECT CAST(COUNT(*) AS INTEGER) AS count FROM checkpoints WHERE card_id = ?
`

// How many restore points a card has. A restore point is made before every turn, and a card
// stopped and resumed many times would otherwise grow a list with no end, so a caller reads this to
// decide whether to trim the oldest.
func (q *Queries) CountCheckpointsForCard(ctx context.Context, cardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckpointsForCard, cardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCheckpoint = `-- name: DeleteCheckpoint :exec
DELETE FROM checkpoints WHERE card_id = ? AND id = ?
`

type DeleteCheckpointParams struct {
	CardID string
	ID     string
}

// Removes one restore point's row. Trimming a card's list goes one row at a time so each removed
// row's hidden ref can be deleted with it, and the commit it pointed at is left for Git's own
// garbage collection. A checkpoint of another card is never removed through this card's address.
func (q *Queries) DeleteCheckpoint(ctx context.Context, arg DeleteCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, deleteCheckpoint, arg.CardID, arg.ID)
	return err
}

const getCheckpoint = `-- name: GetCheckpoint :one
SELECT id, card_id, git_ref, label, created_at FROM checkpoints
WHERE card_id = ? AND id = ?
`

type GetCheckpointParams struct {
	CardID string
	ID     string
}

// One restore point of one card, for a restore asked for by id. The card is part of the lookup so a
// checkpoint of another card can never be restored through this card's address.
func (q *Queries) GetCheckpoint(ctx context.Context, arg GetCheckpointParams) (Checkpoint, error) {
	row := q.db.QueryRowContext(ctx, getCheckpoint, arg.CardID, arg.ID)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.GitRef,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const insertCheckpoint = `-- name: InsertCheckpoint :exec

INSERT INTO checkpoints (id, card_id, git_ref, label, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertCheckpointParams struct {
	ID        string
	CardID    string
	GitRef    string
	Label     string
	CreatedAt int64
}

// A card's checkpoints: the restore points Marshal makes before an agent turn, before a merge, and
// whenever a person asks (docs/architecture.md section 10, docs/backend-checklist.md B5.3). A
// checkpoint is a Git commit on a hidden ref and a row that names it; the card's list is read newest
// first, and a card is removed with its checkpoints (the foreign key in migration 0016).
//
// Nothing here updates a checkpoint: a restore point is a fact about a moment, and the only way one
// changes is by being removed with the card. The id is an opaque id whose first ten characters are
// the time, and created_at, then the id, is what breaks a tie between two made in one millisecond.
// Records one restore point. `git_ref` is the hidden ref the commit is kept on, so a checkpoint can
// be found again after the row is read even if the branch has moved on, and `label` says what it was
// made before ("before turn 3"), and is empty when there is nothing to say.
func (q *Queries) InsertCheckpoint(ctx context.Context, arg InsertCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckpoint,
		arg.ID,
		arg.CardID,
		arg.GitRef,
		arg.Label,
		arg.CreatedAt,
	)
	return err
}

const listCheckpointsForCard = `-- name: ListCheckpointsForCard :many
SELECT id, card_id, git_ref, label, created_at FROM checkpoints
WHERE card_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListCheckpointsForCardParams struct {
	CardID string
	Limit  int64
}

// One card's restore points, newest first, which is the order the card panel shows them in.
func (q *Queries) ListCheckpointsForCard(ctx context.Context, arg ListCheckpointsForCardParams) ([]Checkpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpointsForCard, arg.CardID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkpoint{}
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.GitRef,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
