// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ci.sql

package db

import (
	"context"
)

const getCiRun = `-- name: GetCiRun :one

SELECT id, project_id, card_id, branch, workflow, status, url, started_at, updated_at, rerun_at, fix_sent_at FROM ci_runs WHERE id = ?
`

// Workflow runs and the state they are in (docs/architecture.md sections 9 and 10, docs/
// backend-checklist.md B6.2, build-plan 6.2). The table and its columns are described in migration
// 0018; what matters here is that a row is a workflow's *state* on one branch and not a history, so
// a run that happens again replaces the row it was.
//
// internal/ci is the only writer. It writes from a verified webhook, from the polling backup that
// covers a missed delivery, and from a simulated failure; no route writes a run.
// One run by its id, which is the forge's own run id. sql.ErrNoRows means Marshal has no row for it,
// which is the ordinary state of a run the daemon has not heard about.
func (q *Queries) GetCiRun(ctx context.Context, id string) (CiRun, error) {
	row := q.db.QueryRowContext(ctx, getCiRun, id)
	var i CiRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CardID,
		&i.Branch,
		&i.Workflow,
		&i.Status,
		&i.Url,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.RerunAt,
		&i.FixSentAt,
	)
	return i, err
}

const getCiRunFor = `-- name: GetCiRunFor :one
SELECT id, project_id, card_id, branch, workflow, status, url, started_at, updated_at, rerun_at, fix_sent_at FROM ci_runs WHERE project_id = ? AND branch = ? AND workflow = ?
`

type GetCiRunForParams struct {
	ProjectID string
	Branch    string
	Workflow  string
}

// The newest run of one workflow on one branch: the row a delivery lands on. The unique key of the
// table is exactly these three columns, so this is the lookup the upsert conflicts on.
func (q *Queries) GetCiRunFor(ctx context.Context, arg GetCiRunForParams) (CiRun, error) {
	row := q.db.QueryRowContext(ctx, getCiRunFor, arg.ProjectID, arg.Branch, arg.Workflow)
	var i CiRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CardID,
		&i.Branch,
		&i.Workflow,
		&i.Status,
		&i.Url,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.RerunAt,
		&i.FixSentAt,
	)
	return i, err
}

const listCiRuns = `-- name: ListCiRuns :many
SELECT id, project_id, card_id, branch, workflow, status, url, started_at, updated_at, rerun_at, fix_sent_at FROM ci_runs ORDER BY project_id, updated_at DESC, id
`

// Every run Marshal holds, grouped by project and newest first inside each, which is the order the
// CI health page draws.
func (q *Queries) ListCiRuns(ctx context.Context) ([]CiRun, error) {
	rows, err := q.db.QueryContext(ctx, listCiRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CiRun{}
	for rows.Next() {
		var i CiRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CardID,
			&i.Branch,
			&i.Workflow,
			&i.Status,
			&i.Url,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.RerunAt,
			&i.FixSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCiRunsForCard = `-- name: ListCiRunsForCard :many
SELECT id, project_id, card_id, branch, workflow, status, url, started_at, updated_at, rerun_at, fix_sent_at FROM ci_runs WHERE card_id = ? ORDER BY updated_at DESC, id
`

// One card's runs, newest first, which is what the card's badge and the fix loop read.
func (q *Queries) ListCiRunsForCard(ctx context.Context, cardID *string) ([]CiRun, error) {
	rows, err := q.db.QueryContext(ctx, listCiRunsForCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CiRun{}
	for rows.Next() {
		var i CiRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CardID,
			&i.Branch,
			&i.Workflow,
			&i.Status,
			&i.Url,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.RerunAt,
			&i.FixSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCiRunsForProject = `-- name: ListCiRunsForProject :many
SELECT id, project_id, card_id, branch, workflow, status, url, started_at, updated_at, rerun_at, fix_sent_at FROM ci_runs WHERE project_id = ? ORDER BY updated_at DESC, id
`

// One project's runs, newest first, which is what a project's board and its CI panel read.
func (q *Queries) ListCiRunsForProject(ctx context.Context, projectID string) ([]CiRun, error) {
	rows, err := q.db.QueryContext(ctx, listCiRunsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CiRun{}
	for rows.Next() {
		var i CiRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CardID,
			&i.Branch,
			&i.Workflow,
			&i.Status,
			&i.Url,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.RerunAt,
			&i.FixSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCiRunsWaiting = `-- name: ListCiRunsWaiting :many
SELECT id, project_id, card_id, branch, workflow, status, url, started_at, updated_at, rerun_at, fix_sent_at FROM ci_runs WHERE status IN ('queued', 'running') AND updated_at < ?
ORDER BY project_id, branch, updated_at, id
`

// The runs Marshal is still waiting on that it has not heard about for a while: the queued or
// running ones whose last change is older than the cutoff. This is the polling backup's question
// (section 9): a run the forge finished but whose delivery never arrived stays exactly here. A run
// Marshal is waiting on is a small set at any moment, so the backup's work does not grow with the
// number of runs the daemon has ever seen.
func (q *Queries) ListCiRunsWaiting(ctx context.Context, updatedAt int64) ([]CiRun, error) {
	rows, err := q.db.QueryContext(ctx, listCiRunsWaiting, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CiRun{}
	for rows.Next() {
		var i CiRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CardID,
			&i.Branch,
			&i.Workflow,
			&i.Status,
			&i.Url,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.RerunAt,
			&i.FixSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCiRunFixSent = `-- name: SetCiRunFixSent :exec
UPDATE ci_runs SET fix_sent_at = ? WHERE id = ?
`

type SetCiRunFixSentParams struct {
	FixSentAt int64
	ID        string
}

// Remembers that Marshal sent this run's failed-step log to the card's session, so every later
// delivery of the same failed run records its state without sending the same log again (section 9).
func (q *Queries) SetCiRunFixSent(ctx context.Context, arg SetCiRunFixSentParams) error {
	_, err := q.db.ExecContext(ctx, setCiRunFixSent, arg.FixSentAt, arg.ID)
	return err
}

const setCiRunRerun = `-- name: SetCiRunRerun :exec
UPDATE ci_runs SET rerun_at = ? WHERE id = ?
`

type SetCiRunRerunParams struct {
	RerunAt int64
	ID      string
}

// Remembers that Marshal asked the forge to run this run's failed jobs again, so a second failure of
// the same run sends the trimmed log to the card's session instead of rerunning it forever
// (section 9).
func (q *Queries) SetCiRunRerun(ctx context.Context, arg SetCiRunRerunParams) error {
	_, err := q.db.ExecContext(ctx, setCiRunRerun, arg.RerunAt, arg.ID)
	return err
}

const upsertCiRun = `-- name: UpsertCiRun :exec
INSERT INTO ci_runs (
    id, project_id, card_id, branch, workflow, status, url, started_at, updated_at, rerun_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (project_id, branch, workflow) DO UPDATE SET
    id          = excluded.id,
    card_id     = excluded.card_id,
    status      = excluded.status,
    url         = excluded.url,
    started_at  = excluded.started_at,
    updated_at  = excluded.updated_at,
    rerun_at    = CASE WHEN ci_runs.id = excluded.id THEN ci_runs.rerun_at ELSE 0 END,
    fix_sent_at = CASE WHEN ci_runs.id = excluded.id THEN ci_runs.fix_sent_at ELSE 0 END
`

type UpsertCiRunParams struct {
	ID        string
	ProjectID string
	CardID    *string
	Branch    string
	Workflow  string
	Status    string
	Url       string
	StartedAt int64
	UpdatedAt int64
	RerunAt   int64
}

// Records the newest state of one workflow on one branch, making the row the first time. A run that
// happens again keeps its own run id and lands on the same row, so `rerun_at` - Marshal's memory of
// having already asked for the failed jobs once (section 9) - and `fix_sent_at` - its memory of
// having already sent that run's failure to the card's session - are both kept when the id is
// unchanged and started over at 0 when this is a new run. `card_id` is set to whatever this delivery
// resolved it to, including to NULL for a branch that is not a card's, so a card that is deleted and
// a branch that stops being a card's both end up with the honest answer.
func (q *Queries) UpsertCiRun(ctx context.Context, arg UpsertCiRunParams) error {
	_, err := q.db.ExecContext(ctx, upsertCiRun,
		arg.ID,
		arg.ProjectID,
		arg.CardID,
		arg.Branch,
		arg.Workflow,
		arg.Status,
		arg.Url,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.RerunAt,
	)
	return err
}
