// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
)

const countUnreadComments = `-- name: CountUnreadComments :one
SELECT COUNT(*) FROM comments WHERE card_id = ? AND agent_read_at IS NULL
`

// How many comments are waiting for the agent. The card's "N new" hint reads this, and it is cheap
// enough to ask whenever the card is drawn.
func (q *Queries) CountUnreadComments(ctx context.Context, cardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadComments, cardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachments (id, comment_id, file_name, mime_type, size_bytes, path, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	ID        string
	CommentID string
	FileName  string
	MimeType  string
	SizeBytes int64
	Path      string
	CreatedAt int64
}

// Records a file on a comment. The row is written after the file is on disk, so a row that exists
// points at a file that does too; the service writes the file first and this second, and cleans up
// the file if this fails.
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.ID,
		arg.CommentID,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.Path,
		arg.CreatedAt,
	)
	return err
}

const createComment = `-- name: CreateComment :exec

INSERT INTO comments (id, card_id, author_kind, author_id, body, mentions_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCommentParams struct {
	ID           string
	CardID       string
	AuthorKind   string
	AuthorID     string
	Body         string
	MentionsJSON string
	CreatedAt    int64
}

// Card comments and their attachments (migration 0024, docs/architecture.md section 10's
// `comments` and `attachments` rows and section 19's rules; docs/backend-checklist.md B10.6,
// build-plan tasks 10.12 and 10.13).
//
// A comment is the one place a person writes to the agent outside the chat, and the only content on
// the card that can carry an attachment. The rules that matter - that an attachment is data and
// never run, that a reply wakes the session if needed, that only the author may edit their own
// comment - live in the service; these queries own the order, the cascade, and the agent's read
// marker.
// Makes a comment. `mentions_json` is written with it because a mention is part of what was said,
// not something derived later from the text - a person's handle may be renamed, and the comment
// still has to remember who it named.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.CardID,
		arg.AuthorKind,
		arg.AuthorID,
		arg.Body,
		arg.MentionsJSON,
		arg.CreatedAt,
	)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = ?
`

// Removes one file's row. The file on disk is removed by the service that holds the path; the query
// only ever owns the row, so nothing here reaches outside the database.
func (q *Queries) DeleteAttachment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, id)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?
`

// Removes a comment and, by the cascade, its attachments. Deleting a card removes its comments the
// same way (docs/architecture.md section 19).
func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, card_id, author_kind, author_id, body, mentions_json, agent_read_at, created_at, edited_at FROM comments WHERE id = ?
`

func (q *Queries) GetComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.AuthorKind,
		&i.AuthorID,
		&i.Body,
		&i.MentionsJSON,
		&i.AgentReadAt,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const listCardAttachments = `-- name: ListCardAttachments :many
SELECT attachment.id, attachment.comment_id, attachment.file_name, attachment.mime_type, attachment.size_bytes, attachment.path, attachment.created_at
FROM attachments AS attachment
JOIN comments AS comment ON comment.id = attachment.comment_id
WHERE comment.card_id = ?
ORDER BY attachment.created_at, attachment.id
`

// Every file on a card, for the agent's context and for a card's own file list. It is the join the
// single-comment read does not cover: attachments are asked for per card far more often than per
// comment.
func (q *Queries) ListCardAttachments(ctx context.Context, cardID string) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listCardAttachments, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardComments = `-- name: ListCardComments :many
SELECT id, card_id, author_kind, author_id, body, mentions_json, agent_read_at, created_at, edited_at FROM comments WHERE card_id = ? ORDER BY created_at, id
`

// One card's comments, oldest first, which is the order a conversation is read in.
func (q *Queries) ListCardComments(ctx context.Context, cardID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCardComments, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.AuthorKind,
			&i.AuthorID,
			&i.Body,
			&i.MentionsJSON,
			&i.AgentReadAt,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentAttachments = `-- name: ListCommentAttachments :many
SELECT id, comment_id, file_name, mime_type, size_bytes, path, created_at FROM attachments WHERE comment_id = ? ORDER BY created_at, id
`

// The files on one comment, oldest first.
func (q *Queries) ListCommentAttachments(ctx context.Context, commentID string) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentAttachments, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadComments = `-- name: ListUnreadComments :many
SELECT id, card_id, author_kind, author_id, body, mentions_json, agent_read_at, created_at, edited_at FROM comments
WHERE card_id = ? AND agent_read_at IS NULL
ORDER BY created_at, id
`

// The comments on a card the card's agent has not picked up yet, oldest first. This is what
// `read_comments` hands the agent at the start of a turn, and what marks them read on the way past.
func (q *Queries) ListUnreadComments(ctx context.Context, cardID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadComments, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.AuthorKind,
			&i.AuthorID,
			&i.Body,
			&i.MentionsJSON,
			&i.AgentReadAt,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommentsReadByAgent = `-- name: MarkCommentsReadByAgent :exec
UPDATE comments
SET agent_read_at = ?
WHERE card_id = ? AND agent_read_at IS NULL
`

type MarkCommentsReadByAgentParams struct {
	AgentReadAt *int64
	CardID      string
}

// Records that the card's agent has read what was waiting. It stamps everything the card has that
// is unread, so a marker never lags the answer the agent just acted on.
func (q *Queries) MarkCommentsReadByAgent(ctx context.Context, arg MarkCommentsReadByAgentParams) error {
	_, err := q.db.ExecContext(ctx, markCommentsReadByAgent, arg.AgentReadAt, arg.CardID)
	return err
}

const updateCommentBody = `-- name: UpdateCommentBody :exec
UPDATE comments
SET body = ?, edited_at = ?
WHERE id = ?
`

type UpdateCommentBodyParams struct {
	Body     string
	EditedAt *int64
	ID       string
}

// Edits a comment's words, keeping `created_at` and moving `edited_at`. The mentions are left alone
// on purpose: an edit is to what was written, not to who was named, and re-reading the body for
// mentions would let an edit add an address nobody meant to send to.
func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) error {
	_, err := q.db.ExecContext(ctx, updateCommentBody, arg.Body, arg.EditedAt, arg.ID)
	return err
}
