// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_stats.sql

package db

import (
	"context"
)

const listDailyStats = `-- name: ListDailyStats :many
SELECT day, project_id, cards_finished, merges, ci_failures, cost_micros FROM daily_stats
WHERE day >= ?1 AND day <= ?2
ORDER BY day, project_id
`

type ListDailyStatsParams struct {
	FromDay int64
	ToDay   int64
}

// Every stored day from `from_day` to `to_day`, both midnight in the daemon's own clock, oldest
// first and each day's projects together. The range is inclusive at both ends. The bounds are named
// so the generated parameters are `FromDay` and `ToDay` rather than two parameters called `Day`.
// `SELECT *` keeps the row type the table's own model (`db.DailyStat`), which is what the Home
// answer and the subscriber both read.
func (q *Queries) ListDailyStats(ctx context.Context, arg ListDailyStatsParams) ([]DailyStat, error) {
	rows, err := q.db.QueryContext(ctx, listDailyStats, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStat{}
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(
			&i.Day,
			&i.ProjectID,
			&i.CardsFinished,
			&i.Merges,
			&i.CiFailures,
			&i.CostMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyStat = `-- name: UpsertDailyStat :exec

INSERT INTO daily_stats (day, project_id, cards_finished, merges, ci_failures, cost_micros)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (day, project_id) DO UPDATE SET
    cards_finished = daily_stats.cards_finished + excluded.cards_finished,
    merges = daily_stats.merges + excluded.merges,
    ci_failures = daily_stats.ci_failures + excluded.ci_failures,
    cost_micros = daily_stats.cost_micros + excluded.cost_micros
`

type UpsertDailyStatParams struct {
	Day           int64
	ProjectID     string
	CardsFinished int64
	Merges        int64
	CiFailures    int64
	CostMicros    int64
}

// The pre-computed Home numbers (migration 0008, docs/architecture.md 16.3). Slice D's subscriber
// (internal/dashboard) adds to a day as the daemon's events arrive, and the Home answer reads a
// range of days in one indexed scan. Nothing here ever counts every card.
// Adds one day's numbers to the row for that day and project, making the row when it is the first
// thing that day. Every column is a delta, so the same call can add one finished card, one merge,
// or a whole turn's cost, and a day that is already there keeps what it had. Run in the same
// transaction as the activity row it goes with, so the two never disagree.
func (q *Queries) UpsertDailyStat(ctx context.Context, arg UpsertDailyStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyStat,
		arg.Day,
		arg.ProjectID,
		arg.CardsFinished,
		arg.Merges,
		arg.CiFailures,
		arg.CostMicros,
	)
	return err
}
