// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_stats_recut.sql

package db

import (
	"context"
)

const deleteDailyStatsSince = `-- name: DeleteDailyStatsSince :exec
DELETE FROM daily_stats WHERE day >= ?1
`

// Drops every stored day from `from_day` on, the days a re-cut builds again.
func (q *Queries) DeleteDailyStatsSince(ctx context.Context, fromDay int64) error {
	_, err := q.db.ExecContext(ctx, deleteDailyStatsSince, fromDay)
	return err
}

const listActivityCountsByMinute = `-- name: ListActivityCountsByMinute :many
SELECT project_id,
       CAST(created_at / 60000 * 60000 AS INTEGER) AS minute_ms,
       CAST(COUNT(*) AS INTEGER) AS entries
FROM activity
WHERE kind = ?1 AND created_at >= ?2
GROUP BY project_id, created_at / 60000
ORDER BY project_id, minute_ms
`

type ListActivityCountsByMinuteParams struct {
	Kind  string
	Since int64
}

type ListActivityCountsByMinuteRow struct {
	ProjectID string
	MinuteMs  int64
	Entries   int64
}

// Rebuilds Home's daily numbers in a new zone (dashboard Recut): rows are grouped by the minute here
// and given their day in Go, since a minute never straddles any zone's midnight. This counts the rows
// of one kind at or after `since`; for the merge kind that is the cards counted as finished.
func (q *Queries) ListActivityCountsByMinute(ctx context.Context, arg ListActivityCountsByMinuteParams) ([]ListActivityCountsByMinuteRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityCountsByMinute, arg.Kind, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityCountsByMinuteRow{}
	for rows.Next() {
		var i ListActivityCountsByMinuteRow
		if err := rows.Scan(&i.ProjectID, &i.MinuteMs, &i.Entries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageCostByMinute = `-- name: ListUsageCostByMinute :many
SELECT usage.project_id,
       CAST(usage.created_at / 60000 * 60000 AS INTEGER) AS minute_ms,
       CAST(SUM(usage.cost_micros) AS INTEGER) AS cost_micros
FROM usage
WHERE usage.created_at >= ?1
  AND usage.cost_micros > 0
  AND (usage.project_id = '' OR usage.project_id IN (SELECT id FROM projects))
GROUP BY usage.project_id, usage.created_at / 60000
ORDER BY usage.project_id, minute_ms
`

type ListUsageCostByMinuteRow struct {
	ProjectID  string
	MinuteMs   int64
	CostMicros int64
}

// What the paid model calls at or after `since` cost, per project and minute. A call with no cost
// adds nothing to a day, so it is left out. A removed project's calls are left out too: its
// daily_stats went with it (DeleteDailyStatsForProject) but its usage rows stay.
func (q *Queries) ListUsageCostByMinute(ctx context.Context, since int64) ([]ListUsageCostByMinuteRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsageCostByMinute, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageCostByMinuteRow{}
	for rows.Next() {
		var i ListUsageCostByMinuteRow
		if err := rows.Scan(&i.ProjectID, &i.MinuteMs, &i.CostMicros); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
