// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
)

const listAwakeCards = `-- name: ListAwakeCards :many

SELECT cards.id AS card_id, cards.project_id AS project_id, projects.name AS project_name,
       cards.number AS number, cards.title AS title, cards.state AS state,
       cards.doing_now AS doing_now, cards.pinned AS pinned, cards.paused AS paused,
       cards.context_used AS context_used, sessions.state AS session_state,
       sessions.created_at AS session_started_at
FROM sessions
JOIN cards ON cards.id = sessions.card_id
JOIN projects ON projects.id = cards.project_id
WHERE sessions.state IN ('awake', 'working', 'waking')
ORDER BY sessions.created_at, cards.id
`

type ListAwakeCardsRow struct {
	CardID           string
	ProjectID        string
	ProjectName      string
	Number           int64
	Title            string
	State            string
	DoingNow         string
	Pinned           int64
	Paused           int64
	ContextUsed      int64
	SessionState     string
	SessionStartedAt int64
}

// The Home dashboard's own reads. Slice A builds the first version: the cards that wait on a
// person, the cards with a running session, and the tile counts. Slice D adds the stored daily
// numbers and the activity stream, each in its own file.
// The cards with a session that is awake, working, or waking, oldest session first, so Home shows
// the ones that have run longest at the top.
func (q *Queries) ListAwakeCards(ctx context.Context) ([]ListAwakeCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAwakeCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAwakeCardsRow{}
	for rows.Next() {
		var i ListAwakeCardsRow
		if err := rows.Scan(
			&i.CardID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Number,
			&i.Title,
			&i.State,
			&i.DoingNow,
			&i.Pinned,
			&i.Paused,
			&i.ContextUsed,
			&i.SessionState,
			&i.SessionStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
