// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_links.sql

package db

import (
	"context"
)

const cardExternalID = `-- name: CardExternalID :one
SELECT external_id FROM external_links WHERE card_id = ? AND kind = ? LIMIT 1
`

type CardExternalIDParams struct {
	CardID string
	Kind   string
}

func (q *Queries) CardExternalID(ctx context.Context, arg CardExternalIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, cardExternalID, arg.CardID, arg.Kind)
	var external_id string
	err := row.Scan(&external_id)
	return external_id, err
}

const externalCard = `-- name: ExternalCard :one
SELECT card_id FROM external_links WHERE kind = ? AND external_id = ? LIMIT 1
`

type ExternalCardParams struct {
	Kind       string
	ExternalID string
}

func (q *Queries) ExternalCard(ctx context.Context, arg ExternalCardParams) (string, error) {
	row := q.db.QueryRowContext(ctx, externalCard, arg.Kind, arg.ExternalID)
	var card_id string
	err := row.Scan(&card_id)
	return card_id, err
}

const linkExternal = `-- name: LinkExternal :exec
INSERT INTO external_links (card_id, kind, external_id) VALUES (?, ?, ?)
ON CONFLICT (card_id, kind) DO UPDATE SET external_id = excluded.external_id
`

type LinkExternalParams struct {
	CardID     string
	Kind       string
	ExternalID string
}

func (q *Queries) LinkExternal(ctx context.Context, arg LinkExternalParams) error {
	_, err := q.db.ExecContext(ctx, linkExternal, arg.CardID, arg.Kind, arg.ExternalID)
	return err
}

const unlinkExternal = `-- name: UnlinkExternal :exec
DELETE FROM external_links WHERE card_id = ? AND kind = ?
`

type UnlinkExternalParams struct {
	CardID string
	Kind   string
}

func (q *Queries) UnlinkExternal(ctx context.Context, arg UnlinkExternalParams) error {
	_, err := q.db.ExecContext(ctx, unlinkExternal, arg.CardID, arg.Kind)
	return err
}
