// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_claims.sql

package db

import (
	"context"
)

const deleteFileClaim = `-- name: DeleteFileClaim :exec
DELETE FROM file_claims WHERE card_id = ? AND path_or_package = ?
`

type DeleteFileClaimParams struct {
	CardID        string
	PathOrPackage string
}

// Releases one claim. Releasing one that is not held is not an error: the answer is the same either
// way, which is what `release_files` needs when an agent releases a path twice.
func (q *Queries) DeleteFileClaim(ctx context.Context, arg DeleteFileClaimParams) error {
	_, err := q.db.ExecContext(ctx, deleteFileClaim, arg.CardID, arg.PathOrPackage)
	return err
}

const deleteFileClaimsOfCard = `-- name: DeleteFileClaimsOfCard :exec
DELETE FROM file_claims WHERE card_id = ?
`

// Releases every claim one card holds, for the end of a card's work and for a card that is being
// reset. A card deleted outright needs none of this: the foreign key takes its claims with it.
func (q *Queries) DeleteFileClaimsOfCard(ctx context.Context, cardID string) error {
	_, err := q.db.ExecContext(ctx, deleteFileClaimsOfCard, cardID)
	return err
}

const insertFileClaim = `-- name: InsertFileClaim :exec

INSERT INTO file_claims (card_id, project_id, path_or_package, claimed_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (card_id, path_or_package) DO NOTHING
`

type InsertFileClaimParams struct {
	CardID        string
	ProjectID     string
	PathOrPackage string
	ClaimedAt     int64
}

// Files and packages a card has claimed (migration 0019, docs/architecture.md section 10's
// `file_claims` row and section 11.4's `claim_files` and `release_files`; docs/backend-checklist.md
// B7.2, build-plan task 7.3). internal/memory is the only caller.
//
// A claim is a claim on a thing, not a lock on it. Two cards may hold the same path; what the
// daemon does about that is warn both of them early (B7.2, task 7.3), which is why the overlap read
// below looks for the other card's claim rather than refusing the second one.
// Claims one path for one card. The primary key is (card_id, path_or_package), so claiming a path
// the card already holds is not an error and does not move the claim's time - the same claim is
// still the same claim, and its age is how long the card has had it.
func (q *Queries) InsertFileClaim(ctx context.Context, arg InsertFileClaimParams) error {
	_, err := q.db.ExecContext(ctx, insertFileClaim,
		arg.CardID,
		arg.ProjectID,
		arg.PathOrPackage,
		arg.ClaimedAt,
	)
	return err
}

const listFileClaimsOfCard = `-- name: ListFileClaimsOfCard :many
SELECT card_id, project_id, path_or_package, claimed_at FROM file_claims WHERE card_id = ? ORDER BY claimed_at, path_or_package
`

// One card's claims, oldest first, which is the order an agent claimed them in.
func (q *Queries) ListFileClaimsOfCard(ctx context.Context, cardID string) ([]FileClaim, error) {
	rows, err := q.db.QueryContext(ctx, listFileClaimsOfCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileClaim{}
	for rows.Next() {
		var i FileClaim
		if err := rows.Scan(
			&i.CardID,
			&i.ProjectID,
			&i.PathOrPackage,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileClaimsOfProject = `-- name: ListFileClaimsOfProject :many
SELECT card_id, project_id, path_or_package, claimed_at FROM file_claims WHERE project_id = ? ORDER BY claimed_at, path_or_package
`

// One project's claims, for the board-awareness summary (B7.2, task 7.2) and for the memory
// screens.
func (q *Queries) ListFileClaimsOfProject(ctx context.Context, projectID string) ([]FileClaim, error) {
	rows, err := q.db.QueryContext(ctx, listFileClaimsOfProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileClaim{}
	for rows.Next() {
		var i FileClaim
		if err := rows.Scan(
			&i.CardID,
			&i.ProjectID,
			&i.PathOrPackage,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileClaimsOnPath = `-- name: ListFileClaimsOnPath :many
SELECT card_id, project_id, path_or_package, claimed_at FROM file_claims
WHERE project_id = ? AND path_or_package = ? AND card_id <> ?
`

type ListFileClaimsOnPathParams struct {
	ProjectID     string
	PathOrPackage string
	CardID        string
}

// Who else holds a path in this project. The term `card_id <> ?` is not decoration: it is what
// makes the answer "the other cards" and not "everyone including the card asking", and it lets the
// caller pass "" to ask about every card at once.
func (q *Queries) ListFileClaimsOnPath(ctx context.Context, arg ListFileClaimsOnPathParams) ([]FileClaim, error) {
	rows, err := q.db.QueryContext(ctx, listFileClaimsOnPath, arg.ProjectID, arg.PathOrPackage, arg.CardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileClaim{}
	for rows.Next() {
		var i FileClaim
		if err := rows.Scan(
			&i.CardID,
			&i.ProjectID,
			&i.PathOrPackage,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
