// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package db

import (
	"context"
)

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations WHERE id = ?
`

// Forgets a connection entirely, settings and last result alike. Removing a connection that has no
// row is not an error: the answer is the same list either way, which is how removing a provider key
// that is not there behaves.
func (q *Queries) DeleteIntegration(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIntegration, id)
	return err
}

const getIntegration = `-- name: GetIntegration :one

SELECT id, kind, config_json, keychain_ref, last_test_at, last_test_result_json FROM integrations WHERE id = ?
`

// Connected services and their last connection test (migration 0015, docs/architecture.md section
// 18). internal/connectiontest is the only writer of the two last_test_* columns; a later phase's
// integration module owns config_json and keychain_ref.
// One connection by id. sql.ErrNoRows means Marshal has no row for it yet, which is the state of a
// connection that has never been connected - a provider nobody has saved a key for.
func (q *Queries) GetIntegration(ctx context.Context, id string) (Integration, error) {
	row := q.db.QueryRowContext(ctx, getIntegration, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ConfigJSON,
		&i.KeychainRef,
		&i.LastTestAt,
		&i.LastTestResultJSON,
	)
	return i, err
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, kind, config_json, keychain_ref, last_test_at, last_test_result_json FROM integrations WHERE kind = ? ORDER BY id
`

// Every connection of one kind, by id. The providers Marshal knows are the catalog's own list
// (internal/providers/catalog.go); this is the ones there is a row for, which is the ones that have
// been saved or tested at least once.
func (q *Queries) ListIntegrations(ctx context.Context, kind string) ([]Integration, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrations, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ConfigJSON,
			&i.KeychainRef,
			&i.LastTestAt,
			&i.LastTestResultJSON,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIntegrationTest = `-- name: SetIntegrationTest :exec
INSERT INTO integrations (id, kind, last_test_at, last_test_result_json)
VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    last_test_at          = excluded.last_test_at,
    last_test_result_json = excluded.last_test_result_json
`

type SetIntegrationTestParams struct {
	ID                 string
	Kind               string
	LastTestAt         int64
	LastTestResultJSON string
}

// Records the result of one connection test, making the row the first time. On conflict only the two
// test columns change, so a test never clobbers a connection's settings or its keychain reference.
// The kind is written on insert and left alone afterwards, so the row keeps the kind it was made
// with.
func (q *Queries) SetIntegrationTest(ctx context.Context, arg SetIntegrationTestParams) error {
	_, err := q.db.ExecContext(ctx, setIntegrationTest,
		arg.ID,
		arg.Kind,
		arg.LastTestAt,
		arg.LastTestResultJSON,
	)
	return err
}

const upsertIntegration = `-- name: UpsertIntegration :exec
INSERT INTO integrations (id, kind, config_json, keychain_ref)
VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    kind         = excluded.kind,
    config_json  = excluded.config_json,
    keychain_ref = excluded.keychain_ref
`

type UpsertIntegrationParams struct {
	ID          string
	Kind        string
	ConfigJSON  string
	KeychainRef string
}

// Saves a connection's own settings and the name of its secret, making the row the first time. It
// never touches the two test columns: what is set up and what the last test found are separate
// facts, and saving a new key does not make the last result about the old key disappear - the
// automatic test that follows a save replaces it a moment later (section 18). The kind is written
// on insert so a row always says what sort of connection it is.
func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) error {
	_, err := q.db.ExecContext(ctx, upsertIntegration,
		arg.ID,
		arg.Kind,
		arg.ConfigJSON,
		arg.KeychainRef,
	)
	return err
}
