// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: limits.sql

package db

import (
	"context"
)

const deleteLimit = `-- name: DeleteLimit :exec
DELETE FROM limits WHERE scope = ? AND kind = ?
`

type DeleteLimitParams struct {
	Scope string
	Kind  string
}

// Removes one scope's ceiling of one kind. Removing a ceiling that is not set is not an error: the
// answer to every limits call is the whole list, so a client that clears a field twice reads the
// same answer both times and there is no separate "there was nothing there" to report.
func (q *Queries) DeleteLimit(ctx context.Context, arg DeleteLimitParams) error {
	_, err := q.db.ExecContext(ctx, deleteLimit, arg.Scope, arg.Kind)
	return err
}

const getLimit = `-- name: GetLimit :one

SELECT value FROM limits WHERE scope = ? AND kind = ?
`

type GetLimitParams struct {
	Scope string
	Kind  string
}

// What Marshal is allowed to spend and how many cards it may keep awake (migration 0014,
// docs/architecture.md section 10, inventory B4.5). A limit is a ceiling, not a running total: the
// running total is daily_stats.cost_micros (cost) and the awake list itself (awake). This table is
// tiny and is replaced in place, and a limit the person clears leaves no row.
// One scope's ceiling of one kind. ErrNoSuchLimit (sql.ErrNoRows) means the scope has no ceiling of
// that kind, which is the shipped state: a fresh install limits nothing.
func (q *Queries) GetLimit(ctx context.Context, arg GetLimitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLimit, arg.Scope, arg.Kind)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const listLimits = `-- name: ListLimits :many
SELECT scope, kind, value FROM limits ORDER BY scope, kind
`

// Every ceiling, ordered by (scope, kind) so a reader's answer is stable. This is deliberately not
// the order the settings form shows them in: "global" must come before the project ids and the kinds
// go in cost-day, cost-month, awake order, and both are screen decisions that belong with the
// protocol's own constants, not in SQL (internal/providers/limits.go's sortLimits). The Limits
// section (S26b) reads this to draw the form, and the check that runs before a model call reads it
// once and keeps the answer for the calls that follow.
func (q *Queries) ListLimits(ctx context.Context) ([]Limit, error) {
	rows, err := q.db.QueryContext(ctx, listLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Limit{}
	for rows.Next() {
		var i Limit
		if err := rows.Scan(&i.Scope, &i.Kind, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLimit = `-- name: SetLimit :exec
INSERT INTO limits (scope, kind, value)
VALUES (?, ?, ?)
ON CONFLICT (scope, kind) DO UPDATE SET value = excluded.value
`

type SetLimitParams struct {
	Scope string
	Kind  string
	Value int64
}

// Sets or replaces one scope's ceiling of one kind, so saving twice leaves one row.
func (q *Queries) SetLimit(ctx context.Context, arg SetLimitParams) error {
	_, err := q.db.ExecContext(ctx, setLimit, arg.Scope, arg.Kind, arg.Value)
	return err
}
