// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_servers.sql

package db

import (
	"context"
)

const deleteMCPServer = `-- name: DeleteMCPServer :exec
DELETE FROM mcp_servers WHERE id = ?
`

// Forgets a server entirely. Removing one that has no row is not an error: the answer is the same
// list either way.
func (q *Queries) DeleteMCPServer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMCPServer, id)
	return err
}

const getMCPServer = `-- name: GetMCPServer :one
SELECT id, name, transport_json, health, last_checked_at FROM mcp_servers WHERE id = ?
`

// One server by its own id.
func (q *Queries) GetMCPServer(ctx context.Context, id string) (McpServer, error) {
	row := q.db.QueryRowContext(ctx, getMCPServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TransportJSON,
		&i.Health,
		&i.LastCheckedAt,
	)
	return i, err
}

const getMCPServerByName = `-- name: GetMCPServerByName :one
SELECT id, name, transport_json, health, last_checked_at FROM mcp_servers WHERE name = ?
`

// One server by the name a role names it with. sql.ErrNoRows means a role asks for a server Marshal
// has no row for, which the session start reports rather than silently leaving out.
func (q *Queries) GetMCPServerByName(ctx context.Context, name string) (McpServer, error) {
	row := q.db.QueryRowContext(ctx, getMCPServerByName, name)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TransportJSON,
		&i.Health,
		&i.LastCheckedAt,
	)
	return i, err
}

const listMCPServers = `-- name: ListMCPServers :many

SELECT id, name, transport_json, health, last_checked_at FROM mcp_servers ORDER BY name
`

// The MCP servers Marshal is configured with (migration 0019, docs/architecture.md section 10's
// `mcp_servers` row, section 11.4). The internal MCP server the daemon serves every agent is not
// one of these: it is built into the daemon and always attached (section 11.4), while this table is
// the outside servers a person or a role adds. A role names the ones it wants by name
// (`apps/web/src/mock/seed/settings.ts` seeds `mcp: ["marshal", "github"]`), which is why the name
// is unique and a lookup by name is here beside the lookup by id.
// Every configured server, by name, which is the order a settings screen shows them in.
func (q *Queries) ListMCPServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.QueryContext(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TransportJSON,
			&i.Health,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMCPServerHealth = `-- name: SetMCPServerHealth :exec
INSERT INTO mcp_servers (id, name, health, last_checked_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    health          = excluded.health,
    last_checked_at = excluded.last_checked_at
`

type SetMCPServerHealthParams struct {
	ID            string
	Name          string
	Health        string
	LastCheckedAt int64
}

// Records one check's answer, making the row the first time so a check of a server nobody saved is
// remembered rather than lost. On conflict the name and the transport are left alone.
func (q *Queries) SetMCPServerHealth(ctx context.Context, arg SetMCPServerHealthParams) error {
	_, err := q.db.ExecContext(ctx, setMCPServerHealth,
		arg.ID,
		arg.Name,
		arg.Health,
		arg.LastCheckedAt,
	)
	return err
}

const upsertMCPServer = `-- name: UpsertMCPServer :exec
INSERT INTO mcp_servers (id, name, transport_json)
VALUES (?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name           = excluded.name,
    transport_json = excluded.transport_json
`

type UpsertMCPServerParams struct {
	ID            string
	Name          string
	TransportJSON string
}

// Saves a server's transport, making the row the first time. It never touches the two health
// columns: what a server is set up as and what the last check found are separate facts, the same
// way a connection's settings and its last test are (migration 0015).
func (q *Queries) UpsertMCPServer(ctx context.Context, arg UpsertMCPServerParams) error {
	_, err := q.db.ExecContext(ctx, upsertMCPServer, arg.ID, arg.Name, arg.TransportJSON)
	return err
}
