// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: me.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one

SELECT id, name, email, avatar_path, time_zone, tailnet_identity, created_at, updated_at, avatar_updated_at FROM users WHERE id = ?
`

// The person using Marshal: their profile, avatar, progress, and preferences (internal/accounts).
func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarPath,
		&i.TimeZone,
		&i.TailnetIdentity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, theme, list_columns_json, sort_json, updated_at FROM user_preferences WHERE user_id = ?
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.ListColumnsJSON,
		&i.SortJSON,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProgress = `-- name: GetUserProgress :one
SELECT user_id, onboarding_step, onboarding_done_at, tutorial_done_at, tutorial_skipped, onboarding_skipped FROM user_progress WHERE user_id = ?
`

func (q *Queries) GetUserProgress(ctx context.Context, userID string) (UserProgress, error) {
	row := q.db.QueryRowContext(ctx, getUserProgress, userID)
	var i UserProgress
	err := row.Scan(
		&i.UserID,
		&i.OnboardingStep,
		&i.OnboardingDoneAt,
		&i.TutorialDoneAt,
		&i.TutorialSkipped,
		&i.OnboardingSkipped,
	)
	return i, err
}

const listProjectPreferences = `-- name: ListProjectPreferences :many
SELECT user_id, project_id, last_view, filters_json, "query", swimlane, collapsed_lanes_json, show_all_done, saved_view_id, updated_at FROM project_preferences WHERE user_id = ? ORDER BY project_id
`

func (q *Queries) ListProjectPreferences(ctx context.Context, userID string) ([]ProjectPreference, error) {
	rows, err := q.db.QueryContext(ctx, listProjectPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectPreference{}
	for rows.Next() {
		var i ProjectPreference
		if err := rows.Scan(
			&i.UserID,
			&i.ProjectID,
			&i.LastView,
			&i.FiltersJSON,
			&i.Query,
			&i.Swimlane,
			&i.CollapsedLanesJSON,
			&i.ShowAllDone,
			&i.SavedViewID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, avatar_path, time_zone, tailnet_identity, created_at, updated_at, avatar_updated_at FROM users ORDER BY name, id
`

// Everyone who can be put on a card, by name. Solo use has one row, the owner.
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.AvatarPath,
			&i.TimeZone,
			&i.TailnetIdentity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvatarUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAvatar = `-- name: SetUserAvatar :execrows
UPDATE users SET avatar_path = ?, avatar_updated_at = ?, updated_at = ? WHERE id = ?
`

type SetUserAvatarParams struct {
	AvatarPath      string
	AvatarUpdatedAt *int64
	UpdatedAt       int64
	ID              string
}

// avatar_path is the file name under <data>/avatars, or ” with a NULL avatar_updated_at when the
// avatar is removed.
func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserAvatar,
		arg.AvatarPath,
		arg.AvatarUpdatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users SET name = ?, email = ?, time_zone = ?, updated_at = ? WHERE id = ?
`

type UpdateUserProfileParams struct {
	Name      string
	Email     string
	TimeZone  string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Name,
		arg.Email,
		arg.TimeZone,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertProjectPreferences = `-- name: UpsertProjectPreferences :exec
INSERT INTO project_preferences (
    user_id, project_id, last_view, filters_json, query, swimlane, collapsed_lanes_json,
    show_all_done, saved_view_id, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, project_id) DO UPDATE SET
    last_view = excluded.last_view,
    filters_json = excluded.filters_json,
    query = excluded.query,
    swimlane = excluded.swimlane,
    collapsed_lanes_json = excluded.collapsed_lanes_json,
    show_all_done = excluded.show_all_done,
    saved_view_id = excluded.saved_view_id,
    updated_at = excluded.updated_at
`

type UpsertProjectPreferencesParams struct {
	UserID             string
	ProjectID          string
	LastView           string
	FiltersJSON        string
	Query              string
	Swimlane           string
	CollapsedLanesJSON string
	ShowAllDone        int64
	SavedViewID        *string
	UpdatedAt          int64
}

func (q *Queries) UpsertProjectPreferences(ctx context.Context, arg UpsertProjectPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectPreferences,
		arg.UserID,
		arg.ProjectID,
		arg.LastView,
		arg.FiltersJSON,
		arg.Query,
		arg.Swimlane,
		arg.CollapsedLanesJSON,
		arg.ShowAllDone,
		arg.SavedViewID,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :exec
INSERT INTO user_preferences (user_id, theme, list_columns_json, sort_json, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id) DO UPDATE SET
    theme = excluded.theme,
    list_columns_json = excluded.list_columns_json,
    sort_json = excluded.sort_json,
    updated_at = excluded.updated_at
`

type UpsertUserPreferencesParams struct {
	UserID          string
	Theme           string
	ListColumnsJSON string
	SortJSON        string
	UpdatedAt       int64
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.ListColumnsJSON,
		arg.SortJSON,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserProgress = `-- name: UpsertUserProgress :exec
INSERT INTO user_progress (
    user_id, onboarding_step, onboarding_done_at, onboarding_skipped, tutorial_done_at, tutorial_skipped
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id) DO UPDATE SET
    onboarding_step = excluded.onboarding_step,
    onboarding_done_at = excluded.onboarding_done_at,
    onboarding_skipped = excluded.onboarding_skipped,
    tutorial_done_at = excluded.tutorial_done_at,
    tutorial_skipped = excluded.tutorial_skipped
`

type UpsertUserProgressParams struct {
	UserID            string
	OnboardingStep    int64
	OnboardingDoneAt  *int64
	OnboardingSkipped int64
	TutorialDoneAt    *int64
	TutorialSkipped   int64
}

func (q *Queries) UpsertUserProgress(ctx context.Context, arg UpsertUserProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserProgress,
		arg.UserID,
		arg.OnboardingStep,
		arg.OnboardingDoneAt,
		arg.OnboardingSkipped,
		arg.TutorialDoneAt,
		arg.TutorialSkipped,
	)
	return err
}
