// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge_history.sql

package db

import (
	"context"
)

const getLatestMergeHistoryForCard = `-- name: GetLatestMergeHistoryForCard :one
SELECT id, project_id, card_id, target, merged_at, commit_sha, prev_tip, resolved, summary, backup_branch, wip_ref, folder_tree, undone_at FROM merge_history WHERE card_id = ? ORDER BY merged_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLatestMergeHistoryForCard(ctx context.Context, cardID string) (MergeHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestMergeHistoryForCard, cardID)
	var i MergeHistory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CardID,
		&i.Target,
		&i.MergedAt,
		&i.CommitSha,
		&i.PrevTip,
		&i.Resolved,
		&i.Summary,
		&i.BackupBranch,
		&i.WipRef,
		&i.FolderTree,
		&i.UndoneAt,
	)
	return i, err
}

const getMergeSettings = `-- name: GetMergeSettings :one
SELECT project_id, paused, auto_merge, pending_tip, updated_at FROM project_merge_settings WHERE project_id = ?
`

func (q *Queries) GetMergeSettings(ctx context.Context, projectID string) (ProjectMergeSetting, error) {
	row := q.db.QueryRowContext(ctx, getMergeSettings, projectID)
	var i ProjectMergeSetting
	err := row.Scan(
		&i.ProjectID,
		&i.Paused,
		&i.AutoMerge,
		&i.PendingTip,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMergeHistory = `-- name: InsertMergeHistory :exec

INSERT INTO merge_history (
    id, project_id, card_id, target, merged_at, commit_sha, prev_tip, resolved, summary,
    backup_branch, wip_ref, folder_tree
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMergeHistoryParams struct {
	ID           string
	ProjectID    string
	CardID       string
	Target       string
	MergedAt     int64
	CommitSha    string
	PrevTip      string
	Resolved     int64
	Summary      string
	BackupBranch string
	WipRef       string
	FolderTree   string
}

// What the Integrator delivered, and the settings it merges by (migration 0032, Integrator flow).
func (q *Queries) InsertMergeHistory(ctx context.Context, arg InsertMergeHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertMergeHistory,
		arg.ID,
		arg.ProjectID,
		arg.CardID,
		arg.Target,
		arg.MergedAt,
		arg.CommitSha,
		arg.PrevTip,
		arg.Resolved,
		arg.Summary,
		arg.BackupBranch,
		arg.WipRef,
		arg.FolderTree,
	)
	return err
}

const listMergeHistory = `-- name: ListMergeHistory :many
SELECT h.id, h.project_id, h.card_id, h.target, h.merged_at, h.commit_sha, h.prev_tip, h.resolved,
       h.summary, h.backup_branch, h.wip_ref, h.folder_tree, h.undone_at,
       c.number AS card_number, c.title AS card_title
FROM merge_history h
JOIN cards c ON c.id = h.card_id
WHERE h.project_id = ?
ORDER BY h.merged_at DESC, h.id DESC
LIMIT ?
`

type ListMergeHistoryParams struct {
	ProjectID string
	Limit     int64
}

type ListMergeHistoryRow struct {
	ID           string
	ProjectID    string
	CardID       string
	Target       string
	MergedAt     int64
	CommitSha    string
	PrevTip      string
	Resolved     int64
	Summary      string
	BackupBranch string
	WipRef       string
	FolderTree   string
	UndoneAt     int64
	CardNumber   int64
	CardTitle    string
}

// The newest deliveries of a project, with the card's number and title for the Integration view.
func (q *Queries) ListMergeHistory(ctx context.Context, arg ListMergeHistoryParams) ([]ListMergeHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMergeHistory, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergeHistoryRow{}
	for rows.Next() {
		var i ListMergeHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CardID,
			&i.Target,
			&i.MergedAt,
			&i.CommitSha,
			&i.PrevTip,
			&i.Resolved,
			&i.Summary,
			&i.BackupBranch,
			&i.WipRef,
			&i.FolderTree,
			&i.UndoneAt,
			&i.CardNumber,
			&i.CardTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMergeHistoryUndone = `-- name: MarkMergeHistoryUndone :execrows
UPDATE merge_history SET undone_at = ? WHERE id = ? AND undone_at = 0
`

type MarkMergeHistoryUndoneParams struct {
	UndoneAt int64
	ID       string
}

// Marks a delivery undone, once: a row that is already undone is left alone and reports 0 rows.
func (q *Queries) MarkMergeHistoryUndone(ctx context.Context, arg MarkMergeHistoryUndoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMergeHistoryUndone, arg.UndoneAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setMergeAutoMerge = `-- name: SetMergeAutoMerge :exec
INSERT INTO project_merge_settings (project_id, auto_merge, updated_at) VALUES (?, ?, ?)
ON CONFLICT (project_id) DO UPDATE SET auto_merge = excluded.auto_merge, updated_at = excluded.updated_at
`

type SetMergeAutoMergeParams struct {
	ProjectID string
	AutoMerge int64
	UpdatedAt int64
}

func (q *Queries) SetMergeAutoMerge(ctx context.Context, arg SetMergeAutoMergeParams) error {
	_, err := q.db.ExecContext(ctx, setMergeAutoMerge, arg.ProjectID, arg.AutoMerge, arg.UpdatedAt)
	return err
}

const setMergePaused = `-- name: SetMergePaused :exec
INSERT INTO project_merge_settings (project_id, paused, updated_at) VALUES (?, ?, ?)
ON CONFLICT (project_id) DO UPDATE SET paused = excluded.paused, updated_at = excluded.updated_at
`

type SetMergePausedParams struct {
	ProjectID string
	Paused    int64
	UpdatedAt int64
}

func (q *Queries) SetMergePaused(ctx context.Context, arg SetMergePausedParams) error {
	_, err := q.db.ExecContext(ctx, setMergePaused, arg.ProjectID, arg.Paused, arg.UpdatedAt)
	return err
}

const setMergePendingTip = `-- name: SetMergePendingTip :exec
INSERT INTO project_merge_settings (project_id, pending_tip, updated_at) VALUES (?, ?, ?)
ON CONFLICT (project_id) DO UPDATE SET pending_tip = excluded.pending_tip, updated_at = excluded.updated_at
`

type SetMergePendingTipParams struct {
	ProjectID  string
	PendingTip string
	UpdatedAt  int64
}

func (q *Queries) SetMergePendingTip(ctx context.Context, arg SetMergePendingTipParams) error {
	_, err := q.db.ExecContext(ctx, setMergePendingTip, arg.ProjectID, arg.PendingTip, arg.UpdatedAt)
	return err
}
