// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Board struct {
	ID          string
	ProjectID   string
	ColumnsJSON string
}

type Card struct {
	ID             string
	ProjectID      string
	Number         int64
	BoardID        string
	Title          string
	Body           string
	State          string
	RoleID         string
	AgentKind      string
	Model          string
	Thinking       string
	PermissionMode string
	Branch         string
	WorktreePath   string
	Pinned         int64
	CreatedBy      string
	CreatedAt      int64
	UpdatedAt      int64
}

type Device struct {
	ID         string
	UserID     string
	Name       string
	Kind       string
	TokenHash  string
	PairedAt   int64
	LastSeenAt *int64
	RevokedAt  *int64
}

type Project struct {
	ID             string
	Name           string
	RepoPath       string
	DefaultBranch  string
	Language       string
	DevCommand     string
	BypassLocked   int64
	IsMonorepo     int64
	PackagesJSON   string
	NextCardNumber int64
	CreatedAt      int64
	UpdatedAt      int64
}

type Setting struct {
	Key       string
	ValueJSON string
}

type User struct {
	ID              string
	Name            string
	Email           string
	AvatarPath      string
	TimeZone        string
	TailnetIdentity string
	CreatedAt       int64
	UpdatedAt       int64
}

type UserProgress struct {
	UserID           string
	OnboardingStep   int64
	OnboardingDoneAt *int64
	TutorialDoneAt   *int64
	TutorialSkipped  int64
}
