// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Activity struct {
	ID          string
	Seq         int64
	ProjectID   string
	Kind        string
	SubjectKind string
	SubjectID   string
	SubjectKey  string
	Summary     string
	CreatedAt   int64
}

type Approval struct {
	ID          string
	SessionID   string
	RequestJSON string
	Decision    string
	DecidedBy   string
}

type Attachment struct {
	ID        string
	CommentID string
	FileName  string
	MimeType  string
	SizeBytes int64
	Path      string
	CreatedAt int64
}

type AuditLog struct {
	ID         string
	SessionID  string
	Actor      string
	Action     string
	Target     string
	DetailJSON string
	CreatedAt  int64
}

type Board struct {
	ID          string
	ProjectID   string
	ColumnsJSON string
}

type Card struct {
	ID                string
	ProjectID         string
	Number            int64
	BoardID           string
	Title             string
	Body              string
	State             string
	RoleID            string
	AgentKind         string
	Model             string
	Thinking          string
	PermissionMode    string
	Branch            string
	WorktreePath      string
	Pinned            int64
	CreatedBy         string
	CreatedAt         int64
	UpdatedAt         int64
	Role              string
	Package           string
	PlannedStart      *int64
	PlannedEnd        *int64
	Due               *int64
	ActualStart       *int64
	ActualEnd         *int64
	PullRequestNumber *int64
	PullRequestUrl    string
	CiState           string
	ContextUsed       int64
	NeedsReasonKind   string
	NeedsReasonText   string
	NeedsSince        *int64
	DoingNow          string
	Paused            int64
	ForkedFrom        string
	TemplateID        string
	ParentID          *string
}

type CardCheck struct {
	ID        string
	CardID    string
	Kind      string
	SpecJSON  string
	Status    string
	RunRef    string
	CreatedAt int64
	UpdatedAt int64
}

type CardLabel struct {
	CardID  string
	LabelID string
}

type CardLink struct {
	CardID      string
	DependsOnID string
}

type CardMember struct {
	CardID  string
	UserID  string
	AddedAt int64
}

type Chat struct {
	ID             string
	ProjectID      string
	Title          string
	TargetKind     string
	TargetID       string
	AgentKind      string
	Model          string
	Thinking       string
	PermissionMode string
	ArchivedAt     *int64
	LastActiveAt   int64
	CreatedAt      int64
	UpdatedAt      int64
}

type Checklist struct {
	ID          string
	CardID      string
	Name        string
	Position    int64
	Required    int64
	PeopleOnly  int64
	HideChecked int64
	CreatedAt   int64
	UpdatedAt   int64
}

type ChecklistItem struct {
	ID           string
	ChecklistID  string
	Text         string
	Position     int64
	Done         int64
	DoneByKind   string
	DoneByID     string
	EvidenceJSON string
	DoneAt       *int64
	CreatedAt    int64
	UpdatedAt    int64
}

type Checkpoint struct {
	ID        string
	CardID    string
	GitRef    string
	Label     string
	CreatedAt int64
}

type CiRun struct {
	ID        string
	ProjectID string
	CardID    *string
	Branch    string
	Workflow  string
	Status    string
	Url       string
	StartedAt int64
	UpdatedAt int64
	RerunAt   int64
	FixSentAt int64
}

type Comment struct {
	ID           string
	CardID       string
	AuthorKind   string
	AuthorID     string
	Body         string
	MentionsJSON string
	AgentReadAt  *int64
	CreatedAt    int64
	EditedAt     *int64
}

type DailyStat struct {
	Day           int64
	ProjectID     string
	CardsFinished int64
	Merges        int64
	CiFailures    int64
	CostMicros    int64
}

type Device struct {
	ID         string
	UserID     string
	Name       string
	Kind       string
	TokenHash  string
	PairedAt   int64
	LastSeenAt *int64
	RevokedAt  *int64
}

type ExternalLink struct {
	CardID     string
	Kind       string
	ExternalID string
}

type FileClaim struct {
	CardID        string
	ProjectID     string
	PathOrPackage string
	ClaimedAt     int64
}

type Integration struct {
	ID                 string
	Kind               string
	ConfigJSON         string
	KeychainRef        string
	LastTestAt         int64
	LastTestResultJSON string
}

type Label struct {
	ID        string
	ProjectID string
	Name      string
	Color     string
	CreatedAt int64
}

type Limit struct {
	Scope string
	Kind  string
	Value int64
}

type McpServer struct {
	ID            string
	Name          string
	TransportJSON string
	Health        string
	LastCheckedAt int64
}

type Note struct {
	ID        string
	ProjectID string
	CardID    string
	Kind      string
	Slug      string
	Title     string
	Author    string
	Body      string
	CreatedAt int64
	UpdatedAt int64
}

type NotesFt struct {
	ID        string
	ProjectID string
	CardID    string
	Kind      string
	Title     string
	Body      string
}

type Project struct {
	ID             string
	Name           string
	RepoPath       string
	DefaultBranch  string
	Language       string
	DevCommand     string
	BypassLocked   int64
	IsMonorepo     int64
	PackagesJSON   string
	NextCardNumber int64
	CreatedAt      int64
	UpdatedAt      int64
}

type ProjectPreference struct {
	UserID             string
	ProjectID          string
	LastView           string
	FiltersJSON        string
	Query              string
	Swimlane           string
	CollapsedLanesJSON string
	ShowAllDone        int64
	SavedViewID        *string
	UpdatedAt          int64
}

type Role struct {
	ID        string
	Name      string
	IsStarter int64
	SpecJSON  string
}

type RoleOverride struct {
	RoleID    string
	ProjectID string
	SpecJSON  string
}

type SavedView struct {
	ID          string
	ProjectID   string
	Name        string
	FiltersJSON string
	Swimlane    string
	CreatedAt   int64
	UpdatedAt   int64
}

type Schedule struct {
	ID           string
	ProjectID    string
	Name         string
	Kind         string
	Icon         string
	TriggerType  string
	WhenText     string
	CronExpr     string
	TimeStr      string
	DaysJSON     string
	Action       string
	Enabled      int64
	MissedPolicy string
	CreatedAt    int64
	UpdatedAt    int64
	LastRunAt    int64
}

type ScheduleRun struct {
	ID         string
	ScheduleID string
	RunAt      int64
	Status     string
	Details    string
}

type Session struct {
	ID             string
	CardID         string
	ChatID         *string
	AgentKind      string
	AgentSessionID string
	State          string
	Model          string
	Thinking       string
	PermissionMode string
	LastActiveAt   int64
	CreatedAt      int64
	UpdatedAt      int64
	ViewMode       string
}

type SessionEvent struct {
	ID         string
	CardID     string
	ChatID     *string
	SessionID  string
	Seq        int64
	Kind       string
	State      string
	Summary    string
	DetailJSON string
	LogRef     string
	CreatedAt  int64
}

type SessionEventsFt struct {
	ID      string
	CardID  string
	Summary string
}

type Setting struct {
	Key       string
	ValueJSON string
}

type Skill struct {
	ID     string
	Name   string
	Path   string
	Source string
}

type SmellCheck struct {
	CardID    string
	CommitSha string
	CheckedAt int64
}

type SmellFinding struct {
	ID            string
	CardID        string
	CommitSha     string
	Family        string
	Smell         string
	File          string
	Line          int64
	Severity      string
	Message       string
	Suggestion    string
	Status        string
	DismissReason string
}

type SmellProfile struct {
	ProjectID string
	SpecJSON  string
}

type Template struct {
	ID        string
	Name      string
	SpecJSON  string
	CreatedAt int64
	UpdatedAt int64
}

type Usage struct {
	ID           string
	CardID       string
	ProjectID    string
	RoleID       string
	Provider     string
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostMicros   int64
	CreatedAt    int64
}

type User struct {
	ID              string
	Name            string
	Email           string
	AvatarPath      string
	TimeZone        string
	TailnetIdentity string
	CreatedAt       int64
	UpdatedAt       int64
	AvatarUpdatedAt *int64
}

type UserPreference struct {
	UserID          string
	Theme           string
	ListColumnsJSON string
	SortJSON        string
	UpdatedAt       int64
}

type UserProgress struct {
	UserID            string
	OnboardingStep    int64
	OnboardingDoneAt  *int64
	TutorialDoneAt    *int64
	TutorialSkipped   int64
	OnboardingSkipped int64
}
