// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
)

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM notes WHERE project_id = ? AND slug = ? AND kind = 'lesson'
`

type DeleteLessonParams struct {
	ProjectID string
	Slug      string
}

// Removes one lesson by its slug, for the lessons screen's delete action.
func (q *Queries) DeleteLesson(ctx context.Context, arg DeleteLessonParams) error {
	_, err := q.db.ExecContext(ctx, deleteLesson, arg.ProjectID, arg.Slug)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE project_id = ? AND card_id = ? AND kind = 'card_note'
`

type DeleteNoteParams struct {
	ProjectID string
	CardID    string
}

// Removes a card's note and its indexed text (the delete trigger above). This is for the case where
// the note itself goes away and the card does not, such as a project's memory being kept but its
// notes not: a card deleted outright leaves its note row behind on purpose (migration 0019's header
// comment), so this is also the only way a card note's row is ever removed once its card is gone.
func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteNote, arg.ProjectID, arg.CardID)
	return err
}

const deleteProjectNotes = `-- name: DeleteProjectNotes :exec
DELETE FROM notes WHERE project_id = ?
`

// Removes every note and lesson of one project and the indexed text of each, for a project whose
// memory is being deleted (internal/memory.RemoveProjectMemory). Removing the project outright
// deletes the cards, but that alone leaves a card's own note behind (card_id carries no foreign key,
// migration 0019's header comment) and never touches a lesson at all, so this statement is what
// actually clears a project's notes table, not a backstop for a cascade that would otherwise miss it.
func (q *Queries) DeleteProjectNotes(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectNotes, projectID)
	return err
}

const getLessonBySlug = `-- name: GetLessonBySlug :one
SELECT id, project_id, card_id, kind, slug, title, author, body, created_at, updated_at FROM notes WHERE project_id = ? AND slug = ? AND kind = 'lesson'
`

type GetLessonBySlugParams struct {
	ProjectID string
	Slug      string
}

// One lesson by its slug inside a project. The pair is the unique key for a lesson, the same way
// (project_id, card_id) is for a card's note.
func (q *Queries) GetLessonBySlug(ctx context.Context, arg GetLessonBySlugParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, getLessonBySlug, arg.ProjectID, arg.Slug)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CardID,
		&i.Kind,
		&i.Slug,
		&i.Title,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNote = `-- name: GetNote :one

SELECT id, project_id, card_id, kind, slug, title, author, body, created_at, updated_at FROM notes WHERE project_id = ? AND card_id = ?
`

type GetNoteParams struct {
	ProjectID string
	CardID    string
}

// Card notes, project lessons, and their shared search index (migration 0019, docs/architecture.md
// section 10's `notes` row, section 12's vault layout; docs/backend-checklist.md B7.4, N11, task
// 7.6, and build-plan task 7.12). One table holds both kinds of vault markdown, told apart by
// `kind`, per the owner's decision that a lesson is file-only and indexed the same way a note
// already is rather than in a table of its own. internal/memory is the only caller: it writes the
// file in the vault and this row in the same call, so the two never disagree except while an edit
// in Obsidian is waiting for the watcher (task 7.8).
//
// The FTS index (`notes_fts`, and the triggers that keep it in step) is written and searched from
// internal/memory, and the one search statement is written out by hand in internal/store/
// search_notes.go. sqlc models the virtual table's columns well enough to list them, but it cannot
// parse FTS5's `MATCH` operator: `WHERE notes_fts MATCH ?` and `WHERE f MATCH ?` both stop the
// generator with "column notes_fts does not exist" (measured, not assumed). The statement is a
// Store method rather than SQL in internal/memory because every statement in this codebase lives in
// the package that owns the SQL.
// The note of one card in one project. The pair is the unique key, so this is the whole row and not
// a page of them; sql.ErrNoRows means the card has no note yet, which the memory module reads as
// "hand back the default note" rather than as a missing card (the card is checked through the
// projects service).
func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, arg.ProjectID, arg.CardID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CardID,
		&i.Kind,
		&i.Slug,
		&i.Title,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, project_id, card_id, kind, slug, title, author, body, created_at, updated_at FROM notes WHERE id = ?
`

// One note by its own id, for the reads that come back from search with an id and no project.
func (q *Queries) GetNoteByID(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CardID,
		&i.Kind,
		&i.Slug,
		&i.Title,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLessons = `-- name: ListLessons :many
SELECT id, project_id, card_id, kind, slug, title, author, body, created_at, updated_at FROM notes WHERE project_id = ? AND kind = 'lesson' ORDER BY updated_at DESC
`

// A project's lessons, newest first, for the lessons screen (build-plan task 7.13) and for
// search_memory once combined with a project's card notes (B7.5, section 11.4).
func (q *Queries) ListLessons(ctx context.Context, projectID string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listLessons, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CardID,
			&i.Kind,
			&i.Slug,
			&i.Title,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many
SELECT id, project_id, card_id, kind, slug, title, author, body, created_at, updated_at FROM notes WHERE project_id = ? AND kind = 'card_note' ORDER BY updated_at DESC
`

// A project's card notes, newest first, for the memory screens and for the note half of session
// search (B7.5, S24b). Ordered by the update time so an edited note is the one a person sees first.
// Filtered to card notes: without it, a project's lessons - which share this table (migration 0019)
// - would leak into a list that promises notes.
func (q *Queries) ListNotes(ctx context.Context, projectID string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CardID,
			&i.Kind,
			&i.Slug,
			&i.Title,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLesson = `-- name: UpsertLesson :exec
INSERT INTO notes (id, project_id, kind, slug, title, author, body, created_at, updated_at)
VALUES (?, ?, 'lesson', ?, ?, ?, ?, ?, ?)
ON CONFLICT (project_id, slug) WHERE kind = 'lesson' DO UPDATE SET
    title      = excluded.title,
    author     = excluded.author,
    body       = excluded.body,
    updated_at = excluded.updated_at
`

type UpsertLessonParams struct {
	ID        string
	ProjectID string
	Slug      string
	Title     string
	Author    string
	Body      string
	CreatedAt int64
	UpdatedAt int64
}

// Writes a lesson, making the row the first time. The conflict target is the partial unique index
// that makes "one lesson per slug per project" true among lessons, and the update touches the title,
// the author, the body, and the update time and leaves `id` and `created_at` alone, the same rule
// UpsertNote follows for a card's note.
func (q *Queries) UpsertLesson(ctx context.Context, arg UpsertLessonParams) error {
	_, err := q.db.ExecContext(ctx, upsertLesson,
		arg.ID,
		arg.ProjectID,
		arg.Slug,
		arg.Title,
		arg.Author,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertNote = `-- name: UpsertNote :exec
INSERT INTO notes (id, project_id, card_id, author, body, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (project_id, card_id) WHERE kind = 'card_note' DO UPDATE SET
    author     = excluded.author,
    body       = excluded.body,
    updated_at = excluded.updated_at
`

type UpsertNoteParams struct {
	ID        string
	ProjectID string
	CardID    string
	Author    string
	Body      string
	CreatedAt int64
	UpdatedAt int64
}

// Writes a card's note, making the row the first time. The conflict target is the partial unique
// index that makes "one note per card" true among card notes, and the update touches the body, the
// author, and the update time and leaves `id` and `created_at` alone, so a card's note keeps the id
// and the birthday it was first saved with however many times it is edited.
func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertNote,
		arg.ID,
		arg.ProjectID,
		arg.CardID,
		arg.Author,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
