// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
)

const countNeedsByProject = `-- name: CountNeedsByProject :many
SELECT project_id, CAST(COUNT(*) AS INTEGER) AS needs
FROM cards
WHERE state = 'needs'
GROUP BY project_id
`

type CountNeedsByProjectRow struct {
	ProjectID string
	Needs     int64
}

func (q *Queries) CountNeedsByProject(ctx context.Context) ([]CountNeedsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, countNeedsByProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNeedsByProjectRow{}
	for rows.Next() {
		var i CountNeedsByProjectRow
		if err := rows.Scan(&i.ProjectID, &i.Needs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNeedsForProject = `-- name: CountNeedsForProject :one
SELECT CAST(COUNT(*) AS INTEGER) AS needs FROM cards WHERE project_id = ? AND state = 'needs'
`

func (q *Queries) CountNeedsForProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNeedsForProject, projectID)
	var needs int64
	err := row.Scan(&needs)
	return needs, err
}

const createBoard = `-- name: CreateBoard :exec
INSERT INTO boards (id, project_id, columns_json) VALUES (?, ?, ?)
`

type CreateBoardParams struct {
	ID          string
	ProjectID   string
	ColumnsJSON string
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) error {
	_, err := q.db.ExecContext(ctx, createBoard, arg.ID, arg.ProjectID, arg.ColumnsJSON)
	return err
}

const createCard = `-- name: CreateCard :exec
INSERT INTO cards (
    id, project_id, number, board_id, title, body, state, agent_kind, model, thinking,
    permission_mode, created_by, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCardParams struct {
	ID             string
	ProjectID      string
	Number         int64
	BoardID        string
	Title          string
	Body           string
	State          string
	AgentKind      string
	Model          string
	Thinking       string
	PermissionMode string
	CreatedBy      string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) error {
	_, err := q.db.ExecContext(ctx, createCard,
		arg.ID,
		arg.ProjectID,
		arg.Number,
		arg.BoardID,
		arg.Title,
		arg.Body,
		arg.State,
		arg.AgentKind,
		arg.Model,
		arg.Thinking,
		arg.PermissionMode,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (
    id, name, repo_path, default_branch, language, dev_command,
    bypass_locked, is_monorepo, packages_json, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID            string
	Name          string
	RepoPath      string
	DefaultBranch string
	Language      string
	DevCommand    string
	BypassLocked  int64
	IsMonorepo    int64
	PackagesJSON  string
	CreatedAt     int64
	UpdatedAt     int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.RepoPath,
		arg.DefaultBranch,
		arg.Language,
		arg.DevCommand,
		arg.BypassLocked,
		arg.IsMonorepo,
		arg.PackagesJSON,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBoardByProject = `-- name: GetBoardByProject :one
SELECT id, project_id, columns_json FROM boards WHERE project_id = ?
`

func (q *Queries) GetBoardByProject(ctx context.Context, projectID string) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoardByProject, projectID)
	var i Board
	err := row.Scan(&i.ID, &i.ProjectID, &i.ColumnsJSON)
	return i, err
}

const getCard = `-- name: GetCard :one
SELECT id, project_id, number, board_id, title, body, state, role_id, agent_kind, model, thinking, permission_mode, branch, worktree_path, pinned, created_by, created_at, updated_at FROM cards WHERE id = ?
`

func (q *Queries) GetCard(ctx context.Context, id string) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.BoardID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.RoleID,
		&i.AgentKind,
		&i.Model,
		&i.Thinking,
		&i.PermissionMode,
		&i.Branch,
		&i.WorktreePath,
		&i.Pinned,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardByKey = `-- name: GetCardByKey :one
SELECT id, project_id, number, board_id, title, body, state, role_id, agent_kind, model, thinking, permission_mode, branch, worktree_path, pinned, created_by, created_at, updated_at FROM cards WHERE project_id = ? AND number = ?
`

type GetCardByKeyParams struct {
	ProjectID string
	Number    int64
}

func (q *Queries) GetCardByKey(ctx context.Context, arg GetCardByKeyParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByKey, arg.ProjectID, arg.Number)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.BoardID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.RoleID,
		&i.AgentKind,
		&i.Model,
		&i.Thinking,
		&i.PermissionMode,
		&i.Branch,
		&i.WorktreePath,
		&i.Pinned,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, repo_path, default_branch, language, dev_command, bypass_locked, is_monorepo, packages_json, next_card_number, created_at, updated_at FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoPath,
		&i.DefaultBranch,
		&i.Language,
		&i.DevCommand,
		&i.BypassLocked,
		&i.IsMonorepo,
		&i.PackagesJSON,
		&i.NextCardNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByRepoPath = `-- name: GetProjectByRepoPath :one
SELECT id, name, repo_path, default_branch, language, dev_command, bypass_locked, is_monorepo, packages_json, next_card_number, created_at, updated_at FROM projects WHERE repo_path = ?
`

func (q *Queries) GetProjectByRepoPath(ctx context.Context, repoPath string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByRepoPath, repoPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoPath,
		&i.DefaultBranch,
		&i.Language,
		&i.DevCommand,
		&i.BypassLocked,
		&i.IsMonorepo,
		&i.PackagesJSON,
		&i.NextCardNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardBranches = `-- name: ListCardBranches :many
SELECT branch FROM cards WHERE project_id = ? AND branch <> '' ORDER BY number
`

func (q *Queries) ListCardBranches(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCardBranches, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var branch string
		if err := rows.Scan(&branch); err != nil {
			return nil, err
		}
		items = append(items, branch)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByProject = `-- name: ListCardsByProject :many
SELECT id, project_id, number, board_id, title, body, state, role_id, agent_kind, model, thinking, permission_mode, branch, worktree_path, pinned, created_by, created_at, updated_at FROM cards WHERE project_id = ? ORDER BY number
`

func (q *Queries) ListCardsByProject(ctx context.Context, projectID string) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.BoardID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.RoleID,
			&i.AgentKind,
			&i.Model,
			&i.Thinking,
			&i.PermissionMode,
			&i.Branch,
			&i.WorktreePath,
			&i.Pinned,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, repo_path, default_branch, language, dev_command, bypass_locked, is_monorepo, packages_json, next_card_number, created_at, updated_at FROM projects ORDER BY created_at, id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoPath,
			&i.DefaultBranch,
			&i.Language,
			&i.DevCommand,
			&i.BypassLocked,
			&i.IsMonorepo,
			&i.PackagesJSON,
			&i.NextCardNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectIDExists = `-- name: ProjectIDExists :one
SELECT EXISTS (SELECT 1 FROM projects WHERE id = ?)
`

func (q *Queries) ProjectIDExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectIDExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reserveCardNumber = `-- name: ReserveCardNumber :one
UPDATE projects
SET next_card_number = next_card_number + 1
WHERE id = ?
RETURNING CAST(next_card_number - 1 AS INTEGER) AS number
`

// Takes the next card number of a project and moves the counter on, in one statement. Run it in
// the same transaction as the card insert, so a failed insert gives the number back.
func (q *Queries) ReserveCardNumber(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, reserveCardNumber, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateCardState = `-- name: UpdateCardState :execrows
UPDATE cards SET state = ?, updated_at = ? WHERE id = ?
`

type UpdateCardStateParams struct {
	State     string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateCardState(ctx context.Context, arg UpdateCardStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCardState, arg.State, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCardWorktree = `-- name: UpdateCardWorktree :execrows
UPDATE cards SET worktree_path = ?, branch = ?, updated_at = ? WHERE id = ?
`

type UpdateCardWorktreeParams struct {
	WorktreePath string
	Branch       string
	UpdatedAt    int64
	ID           string
}

func (q *Queries) UpdateCardWorktree(ctx context.Context, arg UpdateCardWorktreeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCardWorktree,
		arg.WorktreePath,
		arg.Branch,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE projects
SET name = ?, dev_command = ?, default_branch = ?, bypass_locked = ?, updated_at = ?
WHERE id = ?
`

type UpdateProjectParams struct {
	Name          string
	DevCommand    string
	DefaultBranch string
	BypassLocked  int64
	UpdatedAt     int64
	ID            string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.DevCommand,
		arg.DefaultBranch,
		arg.BypassLocked,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
