// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quality.sql

package db

import (
	"context"
)

const getSmellCheck = `-- name: GetSmellCheck :one
SELECT checked_at FROM smell_checks WHERE card_id = ? AND commit_sha = ?
`

type GetSmellCheckParams struct {
	CardID    string
	CommitSha string
}

// When the checks last ran for one card and commit, for the per-commit cache. A commit with no row
// has never been checked and is checked now.
func (q *Queries) GetSmellCheck(ctx context.Context, arg GetSmellCheckParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSmellCheck, arg.CardID, arg.CommitSha)
	var checked_at int64
	err := row.Scan(&checked_at)
	return checked_at, err
}

const getSmellFinding = `-- name: GetSmellFinding :one
SELECT id, card_id, commit_sha, family, smell, file, line, severity, message, suggestion, status, dismiss_reason FROM smell_findings
WHERE card_id = ? AND id = ?
`

type GetSmellFindingParams struct {
	CardID string
	ID     string
}

// One finding of one card, for the call that acts on it. The card is part of the lookup so a finding
// of another card can never be fixed or dismissed through this card's address.
func (q *Queries) GetSmellFinding(ctx context.Context, arg GetSmellFindingParams) (SmellFinding, error) {
	row := q.db.QueryRowContext(ctx, getSmellFinding, arg.CardID, arg.ID)
	var i SmellFinding
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.CommitSha,
		&i.Family,
		&i.Smell,
		&i.File,
		&i.Line,
		&i.Severity,
		&i.Message,
		&i.Suggestion,
		&i.Status,
		&i.DismissReason,
	)
	return i, err
}

const getSmellProfile = `-- name: GetSmellProfile :one
SELECT project_id, spec_json FROM smell_profiles WHERE project_id = ?
`

// One project's smell profile. A project that has none reads nothing, and the caller uses the
// built-in defaults.
func (q *Queries) GetSmellProfile(ctx context.Context, projectID string) (SmellProfile, error) {
	row := q.db.QueryRowContext(ctx, getSmellProfile, projectID)
	var i SmellProfile
	err := row.Scan(&i.ProjectID, &i.SpecJSON)
	return i, err
}

const insertSmellFinding = `-- name: InsertSmellFinding :exec

INSERT INTO smell_findings (
    id, card_id, commit_sha, family, smell, file, line, severity, message, suggestion, status, dismiss_reason
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSmellFindingParams struct {
	ID            string
	CardID        string
	CommitSha     string
	Family        string
	Smell         string
	File          string
	Line          int64
	Severity      string
	Message       string
	Suggestion    string
	Status        string
	DismissReason string
}

// The code-smell checks (docs/architecture.md section 17, docs/backend-checklist.md B5.8, build-plan
// 5.20): one project's profile of which checks run at what thresholds, and the findings a check made
// in one card's diff. The two tables and the columns they hold are described in migration 0016.
//
// A finding is written once, when a check runs for a commit, and a check of the same commit does not
// run again: the row in smell_checks is what remembers that a commit was checked, even when the
// check found nothing. After that a finding changes in only two ways - it is dismissed with a reason,
// or it is marked fixed - so nothing here updates a finding's file, line, or words: those are facts
// about the commit it was found in.
//
// The id is an opaque id, and the profile is one JSON document per project; a project with no row
// uses the built-in defaults, which is why GetSmellProfile answers nothing rather than an error for a
// fresh install.
// Records one smell a check found. `commit_sha` is the commit it was found in and is empty for a
// finding from uncommitted work; `family` is the kind of smell, `smell` is the rule's own name, and
// `status` starts open. A finding is inserted with its words and its place, which never change.
func (q *Queries) InsertSmellFinding(ctx context.Context, arg InsertSmellFindingParams) error {
	_, err := q.db.ExecContext(ctx, insertSmellFinding,
		arg.ID,
		arg.CardID,
		arg.CommitSha,
		arg.Family,
		arg.Smell,
		arg.File,
		arg.Line,
		arg.Severity,
		arg.Message,
		arg.Suggestion,
		arg.Status,
		arg.DismissReason,
	)
	return err
}

const listSmellFindingsForCardCommit = `-- name: ListSmellFindingsForCardCommit :many
SELECT id, card_id, commit_sha, family, smell, file, line, severity, message, suggestion, status, dismiss_reason FROM smell_findings
WHERE card_id = ? AND commit_sha = ?
ORDER BY file, line, id
`

type ListSmellFindingsForCardCommitParams struct {
	CardID    string
	CommitSha string
}

// One card's findings as of one commit: the rows a card's checks panel shows, and the rows the move
// to review counts blocking findings from. Findings from an older commit are left where they are,
// because a check of a newer commit must never re-blame a smell on work the card has since changed.
// Ordered by place, so a screen reads them top to bottom of the diff.
func (q *Queries) ListSmellFindingsForCardCommit(ctx context.Context, arg ListSmellFindingsForCardCommitParams) ([]SmellFinding, error) {
	rows, err := q.db.QueryContext(ctx, listSmellFindingsForCardCommit, arg.CardID, arg.CommitSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmellFinding{}
	for rows.Next() {
		var i SmellFinding
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.CommitSha,
			&i.Family,
			&i.Smell,
			&i.File,
			&i.Line,
			&i.Severity,
			&i.Message,
			&i.Suggestion,
			&i.Status,
			&i.DismissReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSmellCheck = `-- name: RecordSmellCheck :exec
INSERT INTO smell_checks (card_id, commit_sha, checked_at)
VALUES (?, ?, ?)
ON CONFLICT (card_id, commit_sha) DO UPDATE SET checked_at = excluded.checked_at
`

type RecordSmellCheckParams struct {
	CardID    string
	CommitSha string
	CheckedAt int64
}

// Remembers that the checks have run for one card and commit, so the same commit is never checked
// twice even when the checks found nothing. A second run of the same commit replaces the time
// rather than writing a second row, which is what the primary key is for.
func (q *Queries) RecordSmellCheck(ctx context.Context, arg RecordSmellCheckParams) error {
	_, err := q.db.ExecContext(ctx, recordSmellCheck, arg.CardID, arg.CommitSha, arg.CheckedAt)
	return err
}

const setSmellFindingStatus = `-- name: SetSmellFindingStatus :exec
UPDATE smell_findings
SET status = ?, dismiss_reason = ?
WHERE card_id = ? AND id = ?
`

type SetSmellFindingStatusParams struct {
	Status        string
	DismissReason string
	CardID        string
	ID            string
}

// Marks one finding fixed or dismissed, and keeps why in `dismiss_reason` for a dismissal (empty for
// a fix). Nothing else about a finding changes: its place and its words are facts about its commit.
func (q *Queries) SetSmellFindingStatus(ctx context.Context, arg SetSmellFindingStatusParams) error {
	_, err := q.db.ExecContext(ctx, setSmellFindingStatus,
		arg.Status,
		arg.DismissReason,
		arg.CardID,
		arg.ID,
	)
	return err
}

const upsertSmellProfile = `-- name: UpsertSmellProfile :exec
INSERT INTO smell_profiles (project_id, spec_json)
VALUES (?, ?)
ON CONFLICT (project_id) DO UPDATE SET spec_json = excluded.spec_json
`

type UpsertSmellProfileParams struct {
	ProjectID string
	SpecJSON  string
}

// Saves one project's smell profile, replacing whatever was there. One profile per project, so this
// is the only write the profile table has.
func (q *Queries) UpsertSmellProfile(ctx context.Context, arg UpsertSmellProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertSmellProfile, arg.ProjectID, arg.SpecJSON)
	return err
}
