// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, name, is_starter, spec_json) VALUES (?, ?, ?, ?)
`

type CreateRoleParams struct {
	ID        string
	Name      string
	IsStarter int64
	SpecJSON  string
}

// Adds a role. A name that is taken is a constraint failure; the service checks first so it can
// answer with a sentence.
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.IsStarter,
		arg.SpecJSON,
	)
	return err
}

const createStarterRole = `-- name: CreateStarterRole :execrows
INSERT INTO roles (id, name, is_starter, spec_json) VALUES (?, ?, 1, ?)
ON CONFLICT (name) DO NOTHING
`

type CreateStarterRoleParams struct {
	ID       string
	Name     string
	SpecJSON string
}

// Adds a starter role if its name is not in use, and does nothing if it is. This is how the daemon
// seeds its starter roles at start-up: a name already there is a role a person has, so their edits
// are left alone and a role is never doubled. It answers how many rows were added, so the seeder can
// say how many were really added.
func (q *Queries) CreateStarterRole(ctx context.Context, arg CreateStarterRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createStarterRole, arg.ID, arg.Name, arg.SpecJSON)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = ?
`

// Removes a role. Every project's override of it goes with it.
func (q *Queries) DeleteRole(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRoleOverride = `-- name: DeleteRoleOverride :exec
DELETE FROM role_overrides WHERE role_id = ? AND project_id = ?
`

type DeleteRoleOverrideParams struct {
	RoleID    string
	ProjectID string
}

// Removes one project's version of one role. Removing an override that is not set is not an error:
// a reset that is asked for twice answers the same list both times.
func (q *Queries) DeleteRoleOverride(ctx context.Context, arg DeleteRoleOverrideParams) error {
	_, err := q.db.ExecContext(ctx, deleteRoleOverride, arg.RoleID, arg.ProjectID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, name, is_starter, spec_json FROM roles WHERE id = ?
`

// One role by its own id. ErrNoSuchRole (sql.ErrNoRows) means no such role.
func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsStarter,
		&i.SpecJSON,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, is_starter, spec_json FROM roles WHERE name = ?
`

// One role by its name, which is unique. This is how the API layer reaches a role, because that is
// what a route, a card, and a chat target name.
func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsStarter,
		&i.SpecJSON,
	)
	return i, err
}

const getRoleOverride = `-- name: GetRoleOverride :one
SELECT role_id, project_id, spec_json FROM role_overrides WHERE role_id = ? AND project_id = ?
`

type GetRoleOverrideParams struct {
	RoleID    string
	ProjectID string
}

// One project's version of one role. ErrNoRows means the project keeps no override and the role's
// own spec is what it uses.
func (q *Queries) GetRoleOverride(ctx context.Context, arg GetRoleOverrideParams) (RoleOverride, error) {
	row := q.db.QueryRowContext(ctx, getRoleOverride, arg.RoleID, arg.ProjectID)
	var i RoleOverride
	err := row.Scan(&i.RoleID, &i.ProjectID, &i.SpecJSON)
	return i, err
}

const listRoleOverridesByProject = `-- name: ListRoleOverridesByProject :many
SELECT role_id, project_id, spec_json FROM role_overrides WHERE project_id = ?
`

// One project's overrides of every role, so a role list can say which roles this project overrides
// without asking once per role.
func (q *Queries) ListRoleOverridesByProject(ctx context.Context, projectID string) ([]RoleOverride, error) {
	rows, err := q.db.QueryContext(ctx, listRoleOverridesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleOverride{}
	for rows.Next() {
		var i RoleOverride
		if err := rows.Scan(&i.RoleID, &i.ProjectID, &i.SpecJSON); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many

SELECT id, name, is_starter, spec_json FROM roles ORDER BY rowid
`

// Roles and per-project role overrides (migration 0016, docs/architecture.md section 10, inventory
// N18). A role is a template the screens edit and a project can keep its own version of. The spec
// is one JSON document and is never read or written piecemeal.
// Every role, in the order the screens show them: Marshal's starter roles first in the order they
// were seeded, then roles a person made in the order they were made. Rowid is that order - a role is
// never moved, and neither a name nor an id orders the list the way the seed does (two ids made in
// the same millisecond differ only in random bits).
func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsStarter,
			&i.SpecJSON,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoleOverride = `-- name: SetRoleOverride :exec
INSERT INTO role_overrides (role_id, project_id, spec_json)
VALUES (?, ?, ?)
ON CONFLICT (role_id, project_id) DO UPDATE SET spec_json = excluded.spec_json
`

type SetRoleOverrideParams struct {
	RoleID    string
	ProjectID string
	SpecJSON  string
}

// Sets or replaces one project's version of one role, so saving twice leaves one row.
func (q *Queries) SetRoleOverride(ctx context.Context, arg SetRoleOverrideParams) error {
	_, err := q.db.ExecContext(ctx, setRoleOverride, arg.RoleID, arg.ProjectID, arg.SpecJSON)
	return err
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE roles SET name = ?, spec_json = ? WHERE id = ?
`

type UpdateRoleParams struct {
	Name     string
	SpecJSON string
	ID       string
}

// Renames a role, replaces its spec, or both. Answers how many rows changed, so a role that went
// away between the read and the write is reported as not found.
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRole, arg.Name, arg.SpecJSON, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
