// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_views.sql

package db

import (
	"context"
)

const createSavedView = `-- name: CreateSavedView :exec
INSERT INTO saved_views (id, project_id, name, filters_json, swimlane, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSavedViewParams struct {
	ID          string
	ProjectID   string
	Name        string
	FiltersJSON string
	Swimlane    string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateSavedView(ctx context.Context, arg CreateSavedViewParams) error {
	_, err := q.db.ExecContext(ctx, createSavedView,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.FiltersJSON,
		arg.Swimlane,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSavedView = `-- name: DeleteSavedView :execrows
DELETE FROM saved_views WHERE id = ?
`

func (q *Queries) DeleteSavedView(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSavedView, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSavedView = `-- name: GetSavedView :one
SELECT id, project_id, name, filters_json, swimlane, created_at, updated_at FROM saved_views WHERE id = ?
`

func (q *Queries) GetSavedView(ctx context.Context, id string) (SavedView, error) {
	row := q.db.QueryRowContext(ctx, getSavedView, id)
	var i SavedView
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.FiltersJSON,
		&i.Swimlane,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSavedViewsByProject = `-- name: ListSavedViewsByProject :many

SELECT id, project_id, name, filters_json, swimlane, created_at, updated_at FROM saved_views WHERE project_id = ? ORDER BY updated_at, id
`

// A project's saved views (internal/projects).
// The order the views were last saved in, which is the order the board's chips are drawn in.
func (q *Queries) ListSavedViewsByProject(ctx context.Context, projectID string) ([]SavedView, error) {
	rows, err := q.db.QueryContext(ctx, listSavedViewsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedView{}
	for rows.Next() {
		var i SavedView
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.FiltersJSON,
			&i.Swimlane,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedView = `-- name: UpdateSavedView :execrows
UPDATE saved_views SET name = ?, filters_json = ?, swimlane = ?, updated_at = ? WHERE id = ?
`

type UpdateSavedViewParams struct {
	Name        string
	FiltersJSON string
	Swimlane    string
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateSavedView(ctx context.Context, arg UpdateSavedViewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSavedView,
		arg.Name,
		arg.FiltersJSON,
		arg.Swimlane,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
