// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package db

import (
	"context"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    id, project_id, name, kind, icon, trigger_type, when_text, cron_expr, time_str, days_json, action, enabled, missed_policy, created_at, updated_at, last_run_at,
    template, sections_json, deliver_json, quiet_when_empty
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, project_id, name, kind, icon, trigger_type, when_text, cron_expr, time_str, days_json, "action", enabled, missed_policy, created_at, updated_at, last_run_at, template, sections_json, deliver_json, quiet_when_empty
`

type CreateScheduleParams struct {
	ID             string
	ProjectID      string
	Name           string
	Kind           string
	Icon           string
	TriggerType    string
	WhenText       string
	CronExpr       string
	TimeStr        string
	DaysJSON       string
	Action         string
	Enabled        int64
	MissedPolicy   string
	CreatedAt      int64
	UpdatedAt      int64
	LastRunAt      int64
	Template       string
	SectionsJSON   string
	DeliverJSON    string
	QuietWhenEmpty int64
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Icon,
		arg.TriggerType,
		arg.WhenText,
		arg.CronExpr,
		arg.TimeStr,
		arg.DaysJSON,
		arg.Action,
		arg.Enabled,
		arg.MissedPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastRunAt,
		arg.Template,
		arg.SectionsJSON,
		arg.DeliverJSON,
		arg.QuietWhenEmpty,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Icon,
		&i.TriggerType,
		&i.WhenText,
		&i.CronExpr,
		&i.TimeStr,
		&i.DaysJSON,
		&i.Action,
		&i.Enabled,
		&i.MissedPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
		&i.Template,
		&i.SectionsJSON,
		&i.DeliverJSON,
		&i.QuietWhenEmpty,
	)
	return i, err
}

const createScheduleRun = `-- name: CreateScheduleRun :one
INSERT INTO schedule_runs (
    id, schedule_id, run_at, status, details
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, schedule_id, run_at, status, details
`

type CreateScheduleRunParams struct {
	ID         string
	ScheduleID string
	RunAt      int64
	Status     string
	Details    string
}

func (q *Queries) CreateScheduleRun(ctx context.Context, arg CreateScheduleRunParams) (ScheduleRun, error) {
	row := q.db.QueryRowContext(ctx, createScheduleRun,
		arg.ID,
		arg.ScheduleID,
		arg.RunAt,
		arg.Status,
		arg.Details,
	)
	var i ScheduleRun
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.RunAt,
		&i.Status,
		&i.Details,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const disableSchedule = `-- name: DisableSchedule :exec
UPDATE schedules SET enabled = 0, updated_at = ? WHERE id = ?
`

type DisableScheduleParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) DisableSchedule(ctx context.Context, arg DisableScheduleParams) error {
	_, err := q.db.ExecContext(ctx, disableSchedule, arg.UpdatedAt, arg.ID)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, project_id, name, kind, icon, trigger_type, when_text, cron_expr, time_str, days_json, "action", enabled, missed_policy, created_at, updated_at, last_run_at, template, sections_json, deliver_json, quiet_when_empty FROM schedules WHERE id = ? LIMIT 1
`

func (q *Queries) GetSchedule(ctx context.Context, id string) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Icon,
		&i.TriggerType,
		&i.WhenText,
		&i.CronExpr,
		&i.TimeStr,
		&i.DaysJSON,
		&i.Action,
		&i.Enabled,
		&i.MissedPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
		&i.Template,
		&i.SectionsJSON,
		&i.DeliverJSON,
		&i.QuietWhenEmpty,
	)
	return i, err
}

const listScheduleRuns = `-- name: ListScheduleRuns :many
SELECT id, schedule_id, run_at, status, details FROM schedule_runs WHERE schedule_id = ? ORDER BY run_at DESC LIMIT ?
`

type ListScheduleRunsParams struct {
	ScheduleID string
	Limit      int64
}

func (q *Queries) ListScheduleRuns(ctx context.Context, arg ListScheduleRunsParams) ([]ScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRuns, arg.ScheduleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleRun{}
	for rows.Next() {
		var i ScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.RunAt,
			&i.Status,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, project_id, name, kind, icon, trigger_type, when_text, cron_expr, time_str, days_json, "action", enabled, missed_policy, created_at, updated_at, last_run_at, template, sections_json, deliver_json, quiet_when_empty FROM schedules ORDER BY created_at ASC
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.Icon,
			&i.TriggerType,
			&i.WhenText,
			&i.CronExpr,
			&i.TimeStr,
			&i.DaysJSON,
			&i.Action,
			&i.Enabled,
			&i.MissedPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.Template,
			&i.SectionsJSON,
			&i.DeliverJSON,
			&i.QuietWhenEmpty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByProject = `-- name: ListSchedulesByProject :many
SELECT id, project_id, name, kind, icon, trigger_type, when_text, cron_expr, time_str, days_json, "action", enabled, missed_policy, created_at, updated_at, last_run_at, template, sections_json, deliver_json, quiet_when_empty FROM schedules WHERE project_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListSchedulesByProject(ctx context.Context, projectID string) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.Icon,
			&i.TriggerType,
			&i.WhenText,
			&i.CronExpr,
			&i.TimeStr,
			&i.DaysJSON,
			&i.Action,
			&i.Enabled,
			&i.MissedPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.Template,
			&i.SectionsJSON,
			&i.DeliverJSON,
			&i.QuietWhenEmpty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules SET
    name = ?,
    trigger_type = ?,
    when_text = ?,
    cron_expr = ?,
    time_str = ?,
    days_json = ?,
    action = ?,
    enabled = ?,
    missed_policy = ?,
    sections_json = ?,
    deliver_json = ?,
    quiet_when_empty = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, project_id, name, kind, icon, trigger_type, when_text, cron_expr, time_str, days_json, "action", enabled, missed_policy, created_at, updated_at, last_run_at, template, sections_json, deliver_json, quiet_when_empty
`

type UpdateScheduleParams struct {
	Name           string
	TriggerType    string
	WhenText       string
	CronExpr       string
	TimeStr        string
	DaysJSON       string
	Action         string
	Enabled        int64
	MissedPolicy   string
	SectionsJSON   string
	DeliverJSON    string
	QuietWhenEmpty int64
	UpdatedAt      int64
	ID             string
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, updateSchedule,
		arg.Name,
		arg.TriggerType,
		arg.WhenText,
		arg.CronExpr,
		arg.TimeStr,
		arg.DaysJSON,
		arg.Action,
		arg.Enabled,
		arg.MissedPolicy,
		arg.SectionsJSON,
		arg.DeliverJSON,
		arg.QuietWhenEmpty,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Icon,
		&i.TriggerType,
		&i.WhenText,
		&i.CronExpr,
		&i.TimeStr,
		&i.DaysJSON,
		&i.Action,
		&i.Enabled,
		&i.MissedPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
		&i.Template,
		&i.SectionsJSON,
		&i.DeliverJSON,
		&i.QuietWhenEmpty,
	)
	return i, err
}

const updateScheduleLastRun = `-- name: UpdateScheduleLastRun :exec
UPDATE schedules SET last_run_at = ?, updated_at = ? WHERE id = ?
`

type UpdateScheduleLastRunParams struct {
	LastRunAt int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateScheduleLastRun(ctx context.Context, arg UpdateScheduleLastRunParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduleLastRun, arg.LastRunAt, arg.UpdatedAt, arg.ID)
	return err
}
