// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, card_id, agent_kind, agent_session_id, state, model, thinking,
    permission_mode, last_active_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID             string
	CardID         string
	AgentKind      string
	AgentSessionID string
	State          string
	Model          string
	Thinking       string
	PermissionMode string
	LastActiveAt   int64
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.CardID,
		arg.AgentKind,
		arg.AgentSessionID,
		arg.State,
		arg.Model,
		arg.Thinking,
		arg.PermissionMode,
		arg.LastActiveAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT id, card_id, agent_kind, agent_session_id, state, model, thinking, permission_mode, last_active_at, created_at, updated_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.AgentKind,
		&i.AgentSessionID,
		&i.State,
		&i.Model,
		&i.Thinking,
		&i.PermissionMode,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByCard = `-- name: GetSessionByCard :one
SELECT id, card_id, agent_kind, agent_session_id, state, model, thinking, permission_mode, last_active_at, created_at, updated_at FROM sessions WHERE card_id = ?
`

func (q *Queries) GetSessionByCard(ctx context.Context, cardID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByCard, cardID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.AgentKind,
		&i.AgentSessionID,
		&i.State,
		&i.Model,
		&i.Thinking,
		&i.PermissionMode,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResumableSessions = `-- name: ListResumableSessions :many
SELECT id, card_id, agent_kind, agent_session_id, state, model, thinking, permission_mode, last_active_at, created_at, updated_at FROM sessions WHERE state IN ('starting', 'awake', 'working') ORDER BY card_id
`

// The states a live session can be in while the daemon runs, in Phase 1: the other states in
// protocol.SessionStateValues (waiting-approval, sleep-warning, asleep, waking) belong to later
// phases and nothing writes them yet.
func (q *Queries) ListResumableSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listResumableSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.AgentKind,
			&i.AgentSessionID,
			&i.State,
			&i.Model,
			&i.Thinking,
			&i.PermissionMode,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionRuntime = `-- name: UpdateSessionRuntime :execrows
UPDATE sessions
SET state = ?, agent_session_id = ?, last_active_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateSessionRuntimeParams struct {
	State          string
	AgentSessionID string
	LastActiveAt   int64
	UpdatedAt      int64
	ID             string
}

func (q *Queries) UpdateSessionRuntime(ctx context.Context, arg UpdateSessionRuntimeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionRuntime,
		arg.State,
		arg.AgentSessionID,
		arg.LastActiveAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
