// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_events.sql

package db

import (
	"context"
)

const getChatEvent = `-- name: GetChatEvent :one
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events WHERE chat_id = ? AND id = ?
`

type GetChatEventParams struct {
	ChatID *string
	ID     string
}

// One of a chat's events in full, for the detail a row opens on demand.
func (q *Queries) GetChatEvent(ctx context.Context, arg GetChatEventParams) (SessionEvent, error) {
	row := q.db.QueryRowContext(ctx, getChatEvent, arg.ChatID, arg.ID)
	var i SessionEvent
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ChatID,
		&i.SessionID,
		&i.Seq,
		&i.Kind,
		&i.State,
		&i.Summary,
		&i.DetailJSON,
		&i.LogRef,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionEvent = `-- name: GetSessionEvent :one
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events WHERE card_id = ? AND card_id <> '' AND id = ?
`

type GetSessionEventParams struct {
	CardID string
	ID     string
}

// One event in full, for the detail a row opens on demand (a tool call's content and diffs).
func (q *Queries) GetSessionEvent(ctx context.Context, arg GetSessionEventParams) (SessionEvent, error) {
	row := q.db.QueryRowContext(ctx, getSessionEvent, arg.CardID, arg.ID)
	var i SessionEvent
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ChatID,
		&i.SessionID,
		&i.Seq,
		&i.Kind,
		&i.State,
		&i.Summary,
		&i.DetailJSON,
		&i.LogRef,
		&i.CreatedAt,
	)
	return i, err
}

const insertChatEvent = `-- name: InsertChatEvent :exec
INSERT INTO session_events (
    id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertChatEventParams struct {
	ID         string
	ChatID     *string
	SessionID  string
	Seq        int64
	Kind       string
	State      string
	Summary    string
	DetailJSON string
	LogRef     string
	CreatedAt  int64
}

// A chat's event: the card side is left at its empty default.
func (q *Queries) InsertChatEvent(ctx context.Context, arg InsertChatEventParams) error {
	_, err := q.db.ExecContext(ctx, insertChatEvent,
		arg.ID,
		arg.ChatID,
		arg.SessionID,
		arg.Seq,
		arg.Kind,
		arg.State,
		arg.Summary,
		arg.DetailJSON,
		arg.LogRef,
		arg.CreatedAt,
	)
	return err
}

const insertSessionEvent = `-- name: InsertSessionEvent :exec

INSERT INTO session_events (
    id, card_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionEventParams struct {
	ID         string
	CardID     string
	SessionID  string
	Seq        int64
	Kind       string
	State      string
	Summary    string
	DetailJSON string
	LogRef     string
	CreatedAt  int64
}

// The append-only history and activity of a session (migration 0006, and 0009 for a chat's). A
// page is read by cursor, newest first: pass the seq the previous page ended on, or 0 for the newest
// page. seq is the owner's own sequence (a card's, or a chat's), so the cursor never skips or
// repeats a row while the session appends.
//
// A card's queries say `card_id <> ”` beside `card_id = ?`. The term is not redundant: a chat's
// event stores ” as its card, and the index that numbers a card's events is partial (WHERE
// card_id <> ”), which SQLite only uses for a query that carries that same term.
func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) error {
	_, err := q.db.ExecContext(ctx, insertSessionEvent,
		arg.ID,
		arg.CardID,
		arg.SessionID,
		arg.Seq,
		arg.Kind,
		arg.State,
		arg.Summary,
		arg.DetailJSON,
		arg.LogRef,
		arg.CreatedAt,
	)
	return err
}

const listChatEvents = `-- name: ListChatEvents :many
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events
WHERE chat_id = ? AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListChatEventsParams struct {
	ChatID *string
	Seq    int64
	Limit  int64
}

func (q *Queries) ListChatEvents(ctx context.Context, arg ListChatEventsParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listChatEvents, arg.ChatID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ChatID,
			&i.SessionID,
			&i.Seq,
			&i.Kind,
			&i.State,
			&i.Summary,
			&i.DetailJSON,
			&i.LogRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEvents = `-- name: ListSessionEvents :many
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events
WHERE card_id = ? AND card_id <> '' AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListSessionEventsParams struct {
	CardID string
	Seq    int64
	Limit  int64
}

func (q *Queries) ListSessionEvents(ctx context.Context, arg ListSessionEventsParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEvents, arg.CardID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ChatID,
			&i.SessionID,
			&i.Seq,
			&i.Kind,
			&i.State,
			&i.Summary,
			&i.DetailJSON,
			&i.LogRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsByKind = `-- name: ListSessionEventsByKind :many
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events
WHERE card_id = ? AND card_id <> '' AND kind = ? AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListSessionEventsByKindParams struct {
	CardID string
	Kind   string
	Seq    int64
	Limit  int64
}

func (q *Queries) ListSessionEventsByKind(ctx context.Context, arg ListSessionEventsByKindParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEventsByKind,
		arg.CardID,
		arg.Kind,
		arg.Seq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ChatID,
			&i.SessionID,
			&i.Seq,
			&i.Kind,
			&i.State,
			&i.Summary,
			&i.DetailJSON,
			&i.LogRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextChatEventSeq = `-- name: NextChatEventSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) + 1 AS INTEGER) AS seq FROM session_events WHERE chat_id = ?
`

// The seq the next event of a chat takes, in the same transaction as the insert.
func (q *Queries) NextChatEventSeq(ctx context.Context, chatID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextChatEventSeq, chatID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const nextSessionEventSeq = `-- name: NextSessionEventSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) + 1 AS INTEGER) AS seq FROM session_events
WHERE card_id = ? AND card_id <> ''
`

// The seq the next event of a card takes. Run it in the same transaction as the insert, so two
// events cannot take one number.
func (q *Queries) NextSessionEventSeq(ctx context.Context, cardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSessionEventSeq, cardID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}
