// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_events.sql

package db

import (
	"context"
)

const countSessionEventsOfKind = `-- name: CountSessionEventsOfKind :one
SELECT CAST(COUNT(*) AS INTEGER) AS count FROM session_events
WHERE card_id = ? AND card_id <> '' AND kind = ?
`

type CountSessionEventsOfKindParams struct {
	CardID string
	Kind   string
}

// How many events of one kind a card has, for a rule that counts rather than pages (the harness's
// round limit, B5.3): one message delivered into a card's session is one turn, and it is stored as
// a user event, so the count of a card's user events is the number of turns the card has taken. It
// counts stored rows, so it survives a restart and a resume.
func (q *Queries) CountSessionEventsOfKind(ctx context.Context, arg CountSessionEventsOfKindParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionEventsOfKind, arg.CardID, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChatEvent = `-- name: GetChatEvent :one
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events WHERE chat_id = ? AND id = ?
`

type GetChatEventParams struct {
	ChatID *string
	ID     string
}

// One of a chat's events in full, for the detail a row opens on demand.
func (q *Queries) GetChatEvent(ctx context.Context, arg GetChatEventParams) (SessionEvent, error) {
	row := q.db.QueryRowContext(ctx, getChatEvent, arg.ChatID, arg.ID)
	var i SessionEvent
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ChatID,
		&i.SessionID,
		&i.Seq,
		&i.Kind,
		&i.State,
		&i.Summary,
		&i.DetailJSON,
		&i.LogRef,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionEvent = `-- name: GetSessionEvent :one
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events WHERE card_id = ? AND card_id <> '' AND id = ?
`

type GetSessionEventParams struct {
	CardID string
	ID     string
}

// One event in full, for the detail a row opens on demand (a tool call's content and diffs).
func (q *Queries) GetSessionEvent(ctx context.Context, arg GetSessionEventParams) (SessionEvent, error) {
	row := q.db.QueryRowContext(ctx, getSessionEvent, arg.CardID, arg.ID)
	var i SessionEvent
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ChatID,
		&i.SessionID,
		&i.Seq,
		&i.Kind,
		&i.State,
		&i.Summary,
		&i.DetailJSON,
		&i.LogRef,
		&i.CreatedAt,
	)
	return i, err
}

const insertChatEvent = `-- name: InsertChatEvent :exec
INSERT INTO session_events (
    id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertChatEventParams struct {
	ID         string
	ChatID     *string
	SessionID  string
	Seq        int64
	Kind       string
	State      string
	Summary    string
	DetailJSON string
	LogRef     string
	CreatedAt  int64
}

// A chat's event: the card side is left at its empty default.
func (q *Queries) InsertChatEvent(ctx context.Context, arg InsertChatEventParams) error {
	_, err := q.db.ExecContext(ctx, insertChatEvent,
		arg.ID,
		arg.ChatID,
		arg.SessionID,
		arg.Seq,
		arg.Kind,
		arg.State,
		arg.Summary,
		arg.DetailJSON,
		arg.LogRef,
		arg.CreatedAt,
	)
	return err
}

const insertSessionEvent = `-- name: InsertSessionEvent :exec

INSERT INTO session_events (
    id, card_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionEventParams struct {
	ID         string
	CardID     string
	SessionID  string
	Seq        int64
	Kind       string
	State      string
	Summary    string
	DetailJSON string
	LogRef     string
	CreatedAt  int64
}

// The append-only history and activity of a session (migration 0006, and 0009 for a chat's). A
// page is read by cursor, newest first: pass the seq the previous page ended on, or 0 for the newest
// page. seq is the owner's own sequence (a card's, or a chat's), so the cursor never skips or
// repeats a row while the session appends.
//
// A card's queries say `card_id <> ”` beside `card_id = ?`. The term is not redundant: a chat's
// event stores ” as its card, and the index that numbers a card's events is partial (WHERE
// card_id <> ”), which SQLite only uses for a query that carries that same term.
func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) error {
	_, err := q.db.ExecContext(ctx, insertSessionEvent,
		arg.ID,
		arg.CardID,
		arg.SessionID,
		arg.Seq,
		arg.Kind,
		arg.State,
		arg.Summary,
		arg.DetailJSON,
		arg.LogRef,
		arg.CreatedAt,
	)
	return err
}

const listChatEvents = `-- name: ListChatEvents :many
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events
WHERE chat_id = ? AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListChatEventsParams struct {
	ChatID *string
	Seq    int64
	Limit  int64
}

func (q *Queries) ListChatEvents(ctx context.Context, arg ListChatEventsParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listChatEvents, arg.ChatID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ChatID,
			&i.SessionID,
			&i.Seq,
			&i.Kind,
			&i.State,
			&i.Summary,
			&i.DetailJSON,
			&i.LogRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatEventsByKind = `-- name: ListChatEventsByKind :many
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events
WHERE chat_id = ? AND kind = ? AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListChatEventsByKindParams struct {
	ChatID *string
	Kind   string
	Seq    int64
	Limit  int64
}

// ListSessionEventsByKind's twin for a chat's history (S8b): used today only to page a chat's own
// approval events while looking for the one an approval's id names (internal/history/approvals.go's
// ResolveApproval), the way ListSessionEventsByKind already does for a card's.
func (q *Queries) ListChatEventsByKind(ctx context.Context, arg ListChatEventsByKindParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listChatEventsByKind,
		arg.ChatID,
		arg.Kind,
		arg.Seq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ChatID,
			&i.SessionID,
			&i.Seq,
			&i.Kind,
			&i.State,
			&i.Summary,
			&i.DetailJSON,
			&i.LogRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEvents = `-- name: ListSessionEvents :many
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events
WHERE card_id = ? AND card_id <> '' AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListSessionEventsParams struct {
	CardID string
	Seq    int64
	Limit  int64
}

func (q *Queries) ListSessionEvents(ctx context.Context, arg ListSessionEventsParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEvents, arg.CardID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ChatID,
			&i.SessionID,
			&i.Seq,
			&i.Kind,
			&i.State,
			&i.Summary,
			&i.DetailJSON,
			&i.LogRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsByKind = `-- name: ListSessionEventsByKind :many
SELECT id, card_id, chat_id, session_id, seq, kind, state, summary, detail_json, log_ref, created_at FROM session_events
WHERE card_id = ? AND card_id <> '' AND kind = ? AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListSessionEventsByKindParams struct {
	CardID string
	Kind   string
	Seq    int64
	Limit  int64
}

func (q *Queries) ListSessionEventsByKind(ctx context.Context, arg ListSessionEventsByKindParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEventsByKind,
		arg.CardID,
		arg.Kind,
		arg.Seq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ChatID,
			&i.SessionID,
			&i.Seq,
			&i.Kind,
			&i.State,
			&i.Summary,
			&i.DetailJSON,
			&i.LogRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextChatEventSeq = `-- name: NextChatEventSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) + 1 AS INTEGER) AS seq FROM session_events WHERE chat_id = ?
`

// The seq the next event of a chat takes, in the same transaction as the insert.
func (q *Queries) NextChatEventSeq(ctx context.Context, chatID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextChatEventSeq, chatID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const nextSessionEventSeq = `-- name: NextSessionEventSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) + 1 AS INTEGER) AS seq FROM session_events
WHERE card_id = ? AND card_id <> ''
`

// The seq the next event of a card takes. Run it in the same transaction as the insert, so two
// events cannot take one number.
func (q *Queries) NextSessionEventSeq(ctx context.Context, cardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSessionEventSeq, cardID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const updateChatEventState = `-- name: UpdateChatEventState :execrows
UPDATE session_events SET state = ?1 WHERE id = ?2 AND chat_id = ?3
`

type UpdateChatEventStateParams struct {
	State  string
	ID     string
	ChatID *string
}

// UpdateSessionEventState's twin for a chat's event.
func (q *Queries) UpdateChatEventState(ctx context.Context, arg UpdateChatEventStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateChatEventState, arg.State, arg.ID, arg.ChatID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSessionEventState = `-- name: UpdateSessionEventState :execrows
UPDATE session_events SET state = ?1 WHERE id = ?2 AND card_id = ?3 AND card_id <> ''
`

type UpdateSessionEventStateParams struct {
	State  string
	ID     string
	CardID string
}

// Rewrites the state of one stored event of a card's history, and nothing else about it (S8b): an
// approval's row is written once, with its own id already in its detail, and this is the one place
// that row is ever touched again, to move it from waiting to however it was answered
// (internal/history/approvals.go's ResolveApproval). id is the event's own id, not the approval's;
// the caller has already found it. Zero rows affected is not an error: see ResolveApproval's doc
// comment on why the row can legitimately not be there.
func (q *Queries) UpdateSessionEventState(ctx context.Context, arg UpdateSessionEventStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionEventState, arg.State, arg.ID, arg.CardID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
