// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value_json FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value_json string
	err := row.Scan(&value_json)
	return value_json, err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value_json) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value_json = excluded.value_json
`

type SetSettingParams struct {
	Key       string
	ValueJSON string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.ValueJSON)
	return err
}
