// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package db

import (
	"context"
)

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = ?
`

// Forgets a skill. Removing one that has no row is not an error, the same as every other delete in
// this module.
func (q *Queries) DeleteSkill(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSkill, id)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, name, path, source FROM skills WHERE id = ?
`

// One skill by its own id.
func (q *Queries) GetSkill(ctx context.Context, id string) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Source,
	)
	return i, err
}

const getSkillByName = `-- name: GetSkillByName :one
SELECT id, name, path, source FROM skills WHERE name = ?
`

// One skill by the name a role names it with. sql.ErrNoRows means the role asks for a skill that is
// not installed.
func (q *Queries) GetSkillByName(ctx context.Context, name string) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkillByName, name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Source,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many

SELECT id, name, path, source FROM skills ORDER BY name
`

// Installed skills (migration 0019, docs/architecture.md section 10's `skills` row, section 12's
// `<data>/skills/`). A role names the skills it wants, the same way it names MCP servers, and this
// table is what those names are resolved against. The skills manager and its screen belong to Phase
// 11 (build-plan task 11.6); Phase 7 stores the registry so a role's skill names can be read back
// and so the session start can say plainly when one is missing.
// Every installed skill, by name.
func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSkill = `-- name: UpsertSkill :exec
INSERT INTO skills (id, name, path, source)
VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name   = excluded.name,
    path   = excluded.path,
    source = excluded.source
`

type UpsertSkillParams struct {
	ID     string
	Name   string
	Path   string
	Source string
}

// Saves a skill's folder and where it came from, making the row the first time.
func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) error {
	_, err := q.db.ExecContext(ctx, upsertSkill,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.Source,
	)
	return err
}
