// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"
)

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM templates
`

// How many templates there are. The settings screen offers the built-in five until a person makes
// their own, and this is what tells it whether they have.
func (q *Queries) CountTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :exec

INSERT INTO templates (id, name, spec_json, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateTemplateParams struct {
	ID        string
	Name      string
	SpecJSON  string
	CreatedAt int64
	UpdatedAt int64
}

// Card templates: the reusable shape a new card starts from (migration 0024, docs/architecture.md
// section 10's `templates` row; docs/backend-checklist.md B10.1, build-plan task 10.1). It replaces
// the fixed five-item picklist the settings screen has today, so it is a table a person can add to.
//
// A template is edited as one thing and read as one thing, which is why its spec is one JSON column
// and every query here reads or writes the whole row rather than its parts.
// Makes a template. A duplicate name is refused by the service with a sentence a person can act on,
// rather than left to the schema: two templates named the same is a person's mistake, and a
// constraint violation would be shown as one.
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.SpecJSON,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = ?
`

// Removes a template. Cards already made from it keep their own copy of what they started with, so
// deleting a template does not rewrite history - it only stops the next card using it.
func (q *Queries) DeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, id)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, spec_json, created_at, updated_at FROM templates WHERE id = ?
`

// One template by id. sql.ErrNoRows means there is no such template, which is how a card made from
// one that has since been deleted is told.
func (q *Queries) GetTemplate(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpecJSON,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, spec_json, created_at, updated_at FROM templates ORDER BY name, id
`

// Every template, in the order the picker shows them: by name, so a person finds theirs without
// scanning. `id` breaks the tie so two templates named alike still come out in the same order twice.
func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpecJSON,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE templates
SET name = ?, spec_json = ?, updated_at = ?
WHERE id = ?
`

type UpdateTemplateParams struct {
	Name      string
	SpecJSON  string
	UpdatedAt int64
	ID        string
}

// Renames a template or replaces its spec. Both are sent together because both are edited in one
// form, and `updated_at` moves so a screen can order templates by when they were last changed.
func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplate,
		arg.Name,
		arg.SpecJSON,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
