// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"
)

const insertUsage = `-- name: InsertUsage :exec

INSERT INTO usage (
    id, card_id, project_id, role_id, provider, model,
    input_tokens, output_tokens, cost_micros, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUsageParams struct {
	ID           string
	CardID       string
	ProjectID    string
	RoleID       string
	Provider     string
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostMicros   int64
	CreatedAt    int64
}

// What Marshal's own model calls cost (migration 0014, docs/architecture.md section 10, inventory
// B4.4). The store's usage writer (internal/providers) inserts one row per provider call and, in the
// same transaction, adds the same cost to that day's daily_stats.cost_micros, so the Home chart and
// the usage detail can never disagree. Nothing here updates or deletes: spend is append-only.
// Records one model call: which provider and model answered, which card, project, and role it ran
// for, what it read and wrote, what that cost in micro-dollars, and when. `id` is an opaque id its
// caller makes, so a caller that retries can recognise the row it already wrote.
func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertUsage,
		arg.ID,
		arg.CardID,
		arg.ProjectID,
		arg.RoleID,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMicros,
		arg.CreatedAt,
	)
	return err
}

const listUsageForCard = `-- name: ListUsageForCard :many
SELECT id, card_id, project_id, role_id, provider, model, input_tokens, output_tokens, cost_micros, created_at FROM usage
WHERE card_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListUsageForCardParams struct {
	CardID string
	Limit  int64
}

// One card's spend, newest first. The card's own page and the card's usage tab read this. The id
// breaks a tie between two calls written in the same millisecond, so a page boundary is stable.
func (q *Queries) ListUsageForCard(ctx context.Context, arg ListUsageForCardParams) ([]Usage, error) {
	rows, err := q.db.QueryContext(ctx, listUsageForCard, arg.CardID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Usage{}
	for rows.Next() {
		var i Usage
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ProjectID,
			&i.RoleID,
			&i.Provider,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMicros,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageForProject = `-- name: ListUsageForProject :many
SELECT id, card_id, project_id, role_id, provider, model, input_tokens, output_tokens, cost_micros, created_at FROM usage
WHERE project_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListUsageForProjectParams struct {
	ProjectID string
	Limit     int64
}

// One project's spend, newest first, which is what the Home cost-per-project chart drills into.
func (q *Queries) ListUsageForProject(ctx context.Context, arg ListUsageForProjectParams) ([]Usage, error) {
	rows, err := q.db.QueryContext(ctx, listUsageForProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Usage{}
	for rows.Next() {
		var i Usage
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ProjectID,
			&i.RoleID,
			&i.Provider,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMicros,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUsageForCard = `-- name: SumUsageForCard :one
SELECT CAST(COALESCE(SUM(cost_micros), 0) AS INTEGER) AS cost_micros FROM usage WHERE card_id = ?
`

// One card's total spend in micro-dollars, which is what the harness reads against a role's own
// cost ceiling (B5.3, docs/architecture.md section 9 step 4). A card with no provider call yet sums
// to zero, so a caller needs no special case for a card that has not spent anything.
func (q *Queries) SumUsageForCard(ctx context.Context, cardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumUsageForCard, cardID)
	var cost_micros int64
	err := row.Scan(&cost_micros)
	return cost_micros, err
}
