// Package codex is the place for the Codex adapter, and for now it only says that there is none.
// Marshal finds Codex and lists it (see agents/catalog), but it cannot start a Codex session, and
// the factory here returns a plain sentence that says so.
//
// This is a choice made from what is documented, and it is written down so that it can be revisited.
// Codex has two documented ways to be driven by a program, and neither is described well enough to
// build against without the real program:
//
//   - "codex exec --json" prints one JSON object per line. The documentation gives a sample and
//     names the kinds of item (messages, reasoning, command runs, file changes, tool calls, web
//     searches, plan updates), but it gives the fields of only two of them, and nothing for a
//     failed turn. It also runs one process for each message, with no way to interrupt a turn or to
//     answer an approval.
//   - "codex app-server" is a JSON-RPC protocol over standard input and output, with threads,
//     turns, interrupts, and approval requests. Its own documentation calls the command
//     experimental, and says that the full message schema is generated by the installed program
//     ("codex app-server generate-json-schema"), one schema for each version.
//
// Codex is not installed on the machine where Marshal was built, so neither could be checked. A fake
// program made from partial samples would only test guesses. The way forward is one of two: build
// the adapter on the app-server protocol once the schema of a real, installed version can be read,
// or run Zed's third-party ACP wrapper for Codex through agents/acp. Either goes in this package,
// behind the same New and Factory.
package codex

import "github.com/khanblair/marshal/daemon/internal/agents"

// Config says how to run Codex. It only holds the place of the program for now.
type Config struct {
	// Path is the codex program, as the catalog found it.
	Path string
}

// NotStartableError is returned by New and by the factory: Marshal has no adapter for Codex yet.
// Its text is a plain sentence that the API layer shows as it is.
type NotStartableError struct{}

// Error says what is and is not possible.
func (NotStartableError) Error() string {
	return "Codex cannot be started from Marshal yet. Use Claude Code or Gemini CLI for now."
}

// New always fails, because there is no Codex adapter yet. The error is a NotStartableError.
func New(Config) (agents.Agent, error) {
	return nil, NotStartableError{}
}

// Factory returns the factory that the session manager registers for the codex kind. Every call of
// it fails with a NotStartableError, so a card that picks Codex gets a sentence instead of a
// session.
func Factory(cfg Config) agents.Factory {
	return func() (agents.Agent, error) { return New(cfg) }
}
